# Generated by Django 5.1.4 on 2026-02-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_personal",
            field=models.BooleanField(default=False),
        ),
    ]
