# Generated by Django 5.1.4 on 2026-03-28 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_add_org_fields_and_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="is_personal",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a user's auto-created personal organization",
                verbose_name="Is Personal",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="Display name of the organization",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                help_text="User who owns this organization",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Unique invite code for joining the organization",
                max_length=12,
                unique=True,
                verbose_name="Invite Code",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this invite",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="default_role",
            field=models.CharField(
                choices=[("editor", "Editor"), ("viewer", "Viewer")],
                default="viewer",
                help_text="Role assigned to users who accept this invite",
                max_length=10,
                verbose_name="Default Role",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this invite expires (null = never)",
                null=True,
                verbose_name="Expires At",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="is_revoked",
            field=models.BooleanField(
                default=False,
                help_text="Whether this invite has been manually revoked",
                verbose_name="Is Revoked",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="max_uses",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of times this invite can be used (null = unlimited)",
                null=True,
                verbose_name="Max Uses",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this invite is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="use_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times this invite has been used",
                verbose_name="Use Count",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this membership belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                help_text="Member's role: owner (full control), editor (create/edit), viewer (read only)",
                max_length=10,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="user",
            field=models.ForeignKey(
                help_text="User who is a member of the organization",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
