# Generated by Django 5.1.4 on 2026-03-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_is_personal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_country",
            field=models.CharField(blank=True, default="US", max_length=2),
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_zip",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
