# Generated by Django 5.1.4 on 2026-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_add_business_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="hubspot_company_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of the corresponding HubSpot Company for CRM sync",
                max_length=50,
                null=True,
                verbose_name="HubSpot Company ID",
            ),
        ),
    ]
