# Generated by Django 5.1.4 on 2026-01-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0005_convert_policy_number_to_policy_numbers_array"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                ("coi_number", models.CharField(max_length=50)),
                ("custom_coi_number", models.CharField(max_length=60, unique=True)),
                ("holder_name", models.CharField(max_length=255)),
                (
                    "holder_second_line",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("holder_street_address", models.CharField(max_length=255)),
                (
                    "holder_suite",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("holder_city", models.CharField(max_length=100)),
                (
                    "holder_state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                            ("DC", "District of Columbia"),
                            ("AS", "American Samoa"),
                            ("GU", "Guam"),
                            ("MP", "Northern Mariana Islands"),
                            ("PR", "Puerto Rico"),
                            ("VI", "Virgin Islands"),
                        ],
                        max_length=2,
                    ),
                ),
                ("holder_zip", models.CharField(max_length=10)),
                ("is_additional_insured", models.BooleanField(default=False)),
                ("endorsements", models.JSONField(default=list)),
                (
                    "service_location_job",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "service_location_address",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "service_you_provide_job",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "service_you_provide_service",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_certificate",
                        to="users.userdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
