# Generated by Django 5.1.4 on 2026-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0004_add_certificate_status_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customcertificate",
            name="coi_number",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
