# Generated by Django 5.1.4 on 2026-03-30 22:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0005_add_performance_indexes"),
        ("organizations", "0007_add_business_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customcertificate",
            unique_together={("user", "organization", "coi_number", "holder_name")},
        ),
    ]
