# Generated by Django 5.1.4 on 2026-03-31 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0006_alter_customcertificate_unique_together"),
        ("organizations", "0007_add_business_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInsured",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "coi_number",
                    models.CharField(
                        db_index=True,
                        help_text="The base COI number this additional insured is linked to.",
                        max_length=50,
                        verbose_name="COI Number",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full legal name of the additional insured.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mailing address of the additional insured.",
                        max_length=500,
                        verbose_name="Address",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email address to send the COI copy to.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number.",
                        max_length=30,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed")],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Removed At"
                    ),
                ),
                (
                    "certificate",
                    models.OneToOneField(
                        blank=True,
                        help_text="The CustomCertificate generated for this additional insured.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additional_insured_record",
                        to="certificates.customcertificate",
                        verbose_name="Generated Certificate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_additional_insureds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="additional_insureds",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_additional_insureds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Removed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Insured",
                "verbose_name_plural": "Additional Insureds",
                "db_table": "additional_insureds",
                "ordering": ["-created_at"],
            },
        ),
    ]
