# Generated by Django 5.1.4 on 2026-01-02 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        help_text="Street address line",
                        max_length=255,
                        verbose_name="Street Address",
                    ),
                ),
                (
                    "suite",
                    models.CharField(
                        blank=True,
                        help_text="Suite, unit, or apartment number",
                        max_length=100,
                        null=True,
                        verbose_name="Suite/Unit",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City name", max_length=100, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                            ("DC", "District of Columbia"),
                            ("AS", "American Samoa"),
                            ("GU", "Guam"),
                            ("MP", "Northern Mariana Islands"),
                            ("PR", "Puerto Rico"),
                            ("VI", "Virgin Islands"),
                        ],
                        help_text="US state or territory",
                        max_length=2,
                        verbose_name="State",
                    ),
                ),
                (
                    "zip",
                    models.CharField(
                        help_text="ZIP or postal code",
                        max_length=10,
                        verbose_name="ZIP Code",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="US",
                        help_text="Country code (default: US)",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("partnership", "Partnership"),
                            ("corporation", "Corporation"),
                            ("llc", "LLC"),
                            ("other", "Other"),
                        ],
                        help_text="Legal structure of the organization",
                        max_length=20,
                        verbose_name="Organization Type",
                    ),
                ),
                (
                    "type_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify organization type if 'Other' is selected",
                        max_length=255,
                        null=True,
                        verbose_name="Other Organization Type",
                    ),
                ),
                (
                    "profit_type",
                    models.CharField(
                        choices=[
                            ("for-profit", "For Profit"),
                            ("not-for-profit", "Not For Profit"),
                        ],
                        help_text="Whether the organization is for-profit or not-for-profit",
                        max_length=20,
                        verbose_name="Profit Type",
                    ),
                ),
                (
                    "last_12_months_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue for the last 12 months",
                        max_digits=15,
                        verbose_name="Last 12 Months Revenue",
                    ),
                ),
                (
                    "projected_next_12_months_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Projected revenue for the next 12 months",
                        max_digits=15,
                        verbose_name="Projected Next 12 Months Revenue",
                    ),
                ),
                (
                    "funding_raised",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total funding raised to date",
                        max_digits=15,
                        null=True,
                        verbose_name="Funding Raised",
                    ),
                ),
                (
                    "funding_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of most recent funding round",
                        null=True,
                        verbose_name="Funding Date",
                    ),
                ),
                (
                    "has_subsidiaries",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the company has subsidiaries",
                        verbose_name="Has Subsidiaries",
                    ),
                ),
                (
                    "all_entities_covered",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether all subsidiary entities are covered",
                        null=True,
                        verbose_name="All Entities Covered",
                    ),
                ),
                (
                    "subsidiaries_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Details about subsidiary entities and coverage",
                        null=True,
                        verbose_name="Subsidiaries Explanation",
                    ),
                ),
                (
                    "planned_acquisitions",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the company has planned acquisitions",
                        verbose_name="Planned Acquisitions",
                    ),
                ),
                (
                    "planned_acquisitions_details",
                    models.TextField(
                        blank=True,
                        help_text="Details about planned acquisitions",
                        null=True,
                        verbose_name="Planned Acquisitions Details",
                    ),
                ),
                (
                    "business_description",
                    models.TextField(
                        help_text="Description of the company's business operations",
                        verbose_name="Business Description",
                    ),
                ),
                (
                    "business_address",
                    models.OneToOneField(
                        help_text="Business address",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company",
                        to="quotes.address",
                        verbose_name="Business Address",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        db_index=True,
                        help_text="Legal name of the organization",
                        max_length=255,
                        verbose_name="Organization Name",
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the applicant",
                        max_length=255,
                        verbose_name="Applicant Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address of the applicant",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number of the applicant",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this contact belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="quotes.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "contacts",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                help_text="Contact person for this company",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="company_contact",
                to="quotes.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Unique quote identifier (auto-generated)",
                        max_length=20,
                        unique=True,
                        verbose_name="Quote Number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("quoted", "Quoted"),
                            ("purchased", "Purchased"),
                            ("declined", "Declined"),
                        ],
                        default="submitted",
                        help_text="Current status of the quote",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "coverages",
                    models.JSONField(
                        default=list,
                        help_text="List of requested coverage types",
                        verbose_name="Coverages",
                    ),
                ),
                (
                    "coverage_data",
                    models.JSONField(
                        default=dict,
                        help_text="Coverage-specific questionnaire data",
                        verbose_name="Coverage Data",
                    ),
                ),
                (
                    "limits_retentions",
                    models.JSONField(
                        default=dict,
                        help_text="Requested limits and retention amounts per coverage",
                        verbose_name="Limits & Retentions",
                    ),
                ),
                (
                    "claims_history",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Loss history and insurance history",
                        null=True,
                        verbose_name="Claims History",
                    ),
                ),
                (
                    "quote_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Final quoted premium amount",
                        max_digits=15,
                        null=True,
                        verbose_name="Quote Amount",
                    ),
                ),
                (
                    "quoted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when quote was provided",
                        null=True,
                        verbose_name="Quoted At",
                    ),
                ),
                (
                    "form_data_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Complete snapshot of submitted form data",
                        verbose_name="Form Data Snapshot",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company requesting the quote",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="quotes.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        help_text="Contact person for this quote",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="quotes.contact",
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
                "db_table": "quotes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="Type/category of document",
                        max_length=50,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original name of the uploaded file",
                        max_length=255,
                        verbose_name="Original Filename",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        help_text="Size of the file in bytes", verbose_name="File Size"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="MIME type of the file",
                        max_length=100,
                        verbose_name="MIME Type",
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        help_text="S3 object key/path",
                        max_length=500,
                        verbose_name="S3 Key",
                    ),
                ),
                (
                    "s3_url",
                    models.URLField(
                        help_text="Full S3 URL to access the file",
                        max_length=1000,
                        verbose_name="S3 URL",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        help_text="Quote this document belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="quotes.quote",
                        verbose_name="Quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Document",
                "verbose_name_plural": "Quote Documents",
                "db_table": "quote_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="contacts_email_2eb381_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["organization_name"], name="contacts_organiz_2e5995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["applicant_name"], name="contacts_applica_980358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["quote_number"], name="quotes_quote_n_a300f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["status"], name="quotes_status_b396a9_idx"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["-created_at"], name="quotes_created_8651f8_idx"
            ),
        ),
    ]
