# Generated by Django 5.1.4 on 2026-01-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="business_address",
            field=models.OneToOneField(
                help_text="Business address",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="quotes.address",
                verbose_name="Business Address",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                help_text="Contact person for this company",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_contact",
                to="quotes.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="company",
            field=models.ForeignKey(
                help_text="Company requesting the quote",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="quotes.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="contact",
            field=models.ForeignKey(
                help_text="Contact person for this quote",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="quotes.contact",
                verbose_name="Contact",
            ),
        ),
    ]
