# Generated by Django 5.1.4 on 2026-01-04 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_change_protect_to_cascade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotedocument",
            options={},
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="file_size",
            field=models.BigIntegerField(help_text="Size in bytes"),
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="file_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="mime_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="original_filename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="quotes.quote",
            ),
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="s3_key",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="quotedocument",
            name="s3_url",
            field=models.URLField(max_length=1000),
        ),
    ]
