# Generated by Django 5.1.4 on 2026-01-04 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_alter_quotedocument_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user who submitted the quote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
