# Generated by Django 5.1.4 on 2026-01-04 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_quote_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="contact",
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(
                default="",
                help_text="Legal name of the company",
                max_length=255,
                verbose_name="Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the quote",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
