# Generated by Django 5.1.4 on 2026-01-04 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_remove_company_contact_remove_quote_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="name",
        ),
    ]
