# Generated by Django 5.1.4 on 2026-01-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_remove_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("needs_review", "Needs Review"),
                    ("quoted", "Quoted"),
                    ("purchased", "Purchased"),
                    ("declined", "Declined"),
                ],
                default="submitted",
                help_text="Current status of the quote",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
