# Generated by Django 5.1.4 on 2026-01-06 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0008_add_ai_calculation_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="funding_date",
        ),
        migrations.RemoveField(
            model_name="company",
            name="funding_raised",
        ),
    ]
