# Generated by Django 5.1.4 on 2026-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0011_alter_quote_rating_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="payment_link",
            field=models.URLField(
                blank=True,
                help_text="Stripe payment link for purchasing the policy",
                max_length=500,
                null=True,
                verbose_name="Payment Link",
            ),
        ),
    ]
