# Generated by Django 5.1.4 on 2026-01-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0012_add_payment_link_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="billing_frequency",
            field=models.CharField(
                choices=[("annual", "Annual"), ("monthly", "Monthly")],
                default="annual",
                help_text="Payment frequency selected by the customer (annual or monthly)",
                max_length=10,
                verbose_name="Billing Frequency",
            ),
        ),
    ]
