# Generated by Django 5.1.4 on 2026-01-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0013_quote_billing_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="entity_legal_name",
            field=models.CharField(
                default="",
                help_text="Legal name of the organization",
                max_length=255,
                verbose_name="Entity Legal Name",
            ),
        ),
    ]
