# Generated by Django 5.1.4 on 2026-01-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0014_add_entity_legal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="promo_code",
            field=models.CharField(
                blank=True,
                help_text="Promotional code from landing page to be auto-applied at checkout",
                max_length=50,
                null=True,
                verbose_name="Promo Code",
            ),
        ),
    ]
