# Generated by Django 5.1.4 on 2026-01-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0015_add_promo_code_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="completed_steps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of step IDs that have been completed",
                verbose_name="Completed Steps",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="current_step",
            field=models.CharField(
                blank=True,
                help_text="The current step ID where the user left off",
                max_length=100,
                null=True,
                verbose_name="Current Step",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("needs_review", "Needs Review"),
                    ("quoted", "Quoted"),
                    ("purchased", "Purchased"),
                    ("declined", "Declined"),
                ],
                default="submitted",
                help_text="Current status of the quote",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
