# Generated by Django 5.1.4 on 2026-01-14

from django.db import migrations


def populate_completed_steps(apps, schema_editor):
    """
    Populate completed_steps and current_step for existing quotes.

    For quotes that were created before the draft flow was implemented:
    - If status is 'submitted', 'quoted', 'needs_review', or 'purchased': they completed the full flow
    - If status is 'draft': leave them as-is (they're in progress)
    """
    Quote = apps.get_model("quotes", "Quote")

    # Get all quotes that have been submitted/quoted - they should have full completed_steps
    # This includes quotes with empty list OR partial list (missing 'summary')
    submitted_quotes = Quote.objects.filter(
        status__in=["submitted", "quoted", "needs_review", "purchased"]
    ).exclude(
        completed_steps__contains="summary"  # Skip if already has summary (fully populated)
    )

    count = 0
    for quote in submitted_quotes:
        # Build completed_steps based on the coverages
        completed_steps = [
            "welcome",
            "package-selection",
            "products",
            "business-address",
            "organization-info",
            "financial-details",
            "structure-operations",
        ]

        # Add coverage-specific steps
        coverages = quote.coverages or []
        for coverage in coverages:
            completed_steps.append(coverage)

        # Add claims history and final steps
        completed_steps.extend(
            [
                "insurance-history",
                "loss-history",
                "notices-signatures",
                "summary",
            ]
        )

        quote.completed_steps = completed_steps
        quote.current_step = "summary"
        quote.save(update_fields=["completed_steps", "current_step"])
        count += 1

    print(f"Updated {count} quotes with completed_steps")


def reverse_populate_completed_steps(apps, schema_editor):
    """Reverse: clear completed_steps for quotes that were populated by this migration."""
    Quote = apps.get_model("quotes", "Quote")
    Quote.objects.filter(
        status__in=["submitted", "quoted", "needs_review", "purchased"]
    ).update(completed_steps=[], current_step=None)


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0016_add_draft_status_and_step_tracking"),
    ]

    operations = [
        migrations.RunPython(
            populate_completed_steps, reverse_populate_completed_steps
        ),
    ]
