# Generated by Django 5.1.4 on 2026-01-14 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0017_populate_completed_steps_for_existing_quotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this custom product",
                        max_length=255,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("eo", "Errors & Omissions"),
                            ("do", "Directors & Officers"),
                            ("cyber", "Cyber Liability"),
                            ("epli", "Employment Practices Liability"),
                            ("fiduciary", "Fiduciary Liability"),
                            ("crime", "Crime"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Product Type",
                    ),
                ),
                (
                    "per_occurrence_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Per Occurrence Limit"
                    ),
                ),
                (
                    "aggregate_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Aggregate Limit"
                    ),
                ),
                (
                    "retention",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Retention"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual premium for this custom product",
                        max_digits=15,
                        verbose_name="Price",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("s3_key", models.CharField(blank=True, max_length=500, null=True)),
                ("s3_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_products",
                        to="quotes.quote",
                        verbose_name="Quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Product",
                "verbose_name_plural": "Custom Products",
                "db_table": "custom_products",
            },
        ),
    ]
