# Generated by Django 5.1.4 on 2026-01-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0018_add_custom_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customproduct",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("custom-cgl", "Commercial General Liability (CGL)"),
                    ("custom-do", "Directors & Officers (D&O)"),
                    ("custom-eo", "Errors & Omissions (E&O)"),
                    ("custom-tech-eo", "Technology E&O"),
                    ("custom-cyber", "Cyber Liability"),
                    ("custom-epli", "Employment Practices Liability (EPLI)"),
                    ("custom-workers-comp", "Workers Compensation"),
                    ("custom-umbrella", "Umbrella / Excess Liability"),
                    ("custom-hnoa", "Hired & Non-Owned Auto (HNOA)"),
                    ("custom-crime", "Crime Insurance"),
                    ("custom-property", "Commercial Property"),
                    ("custom-surety", "Surety Bond"),
                    ("custom-fiduciary", "Fiduciary Liability"),
                    ("custom-other", "Other"),
                ],
                max_length=50,
                verbose_name="Product Type",
            ),
        ),
    ]
