# Generated by Django 5.1.4 on 2026-01-15 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0020_add_effective_date_to_quote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_link",
        ),
    ]
