# Generated by Django 5.1.4 on 2026-01-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0021_remove_quote_effective_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_technology_company",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the company develops, uses, or relies on technology as a core part of its operations",
                null=True,
                verbose_name="Is Technology Company",
            ),
        ),
    ]
