# Generated by Django 5.1.4 on 2026-01-19 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0023_update_hnoa_driver_band_3_5_to_0_5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnderwriterOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "coverage",
                    models.CharField(
                        choices=[
                            (
                                "commercial-general-liability",
                                "Commercial General Liability",
                            ),
                            ("media-liability", "Media Liability"),
                            ("directors-and-officers", "Directors & Officers"),
                            (
                                "representations-warranties",
                                "Representations & Warranties",
                            ),
                            ("technology-errors-and-omissions", "Technology E&O"),
                            ("cyber-liability", "Cyber Liability"),
                            ("fiduciary-liability", "Fiduciary Liability"),
                            ("hired-and-non-owned-auto", "Hired & Non-Owned Auto"),
                            (
                                "employment-practices-liability",
                                "Employment Practices Liability",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Coverage",
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier applied to the calculated premium (1.0 = no change, 1.5 = 50% increase, 0.8 = 20% discount)",
                        max_digits=5,
                        verbose_name="Premium Multiplier",
                    ),
                ),
                (
                    "bypass_validation",
                    models.BooleanField(
                        default=True,
                        help_text="If true, skip validation errors for this coverage and use the multiplier on base premium",
                        verbose_name="Bypass Validation",
                    ),
                ),
                (
                    "override_premium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="If set, use this exact premium instead of calculating (ignores multiplier)",
                        max_digits=15,
                        null=True,
                        verbose_name="Override Premium",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Explanation for the override decision",
                        verbose_name="Underwriter Comment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="underwriter_overrides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="underwriter_overrides",
                        to="quotes.quote",
                        verbose_name="Quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Underwriter Override",
                "verbose_name_plural": "Underwriter Overrides",
                "db_table": "underwriter_overrides",
                "unique_together": {("quote", "coverage")},
            },
        ),
    ]
