# Generated by Django 5.1.4 on 2026-01-19 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0024_add_underwriter_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="underwriteroverride",
            name="override_premium",
        ),
    ]
