# Generated by Django 5.1.4 on 2026-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0025_remove_override_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="customproduct",
            name="carrier",
            field=models.CharField(
                blank=True,
                help_text="Insurance carrier for this custom product",
                max_length=255,
                null=True,
                verbose_name="Carrier",
            ),
        ),
    ]
