# Generated by Django 5.1.4 on 2026-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0026_add_carrier_to_custom_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="federal_ein",
            field=models.CharField(
                blank=True,
                help_text="Federal Employer Identification Number (empty if not applicable)",
                max_length=20,
                null=True,
                verbose_name="Federal EIN",
            ),
        ),
    ]
