# Generated by Django 5.1.4 on 2026-01-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0027_add_federal_ein_to_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="full_time_employees",
            field=models.IntegerField(
                blank=True,
                help_text="Number of full time employees",
                null=True,
                verbose_name="Full Time Employees",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="part_time_employees",
            field=models.IntegerField(
                blank=True,
                help_text="Number of part time employees",
                null=True,
                verbose_name="Part Time Employees",
            ),
        ),
    ]
