# Generated by Django 5.1.4 on 2026-01-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0028_add_employee_counts_to_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="available_coverages",
            field=models.JSONField(
                default=list,
                help_text="List of all coverages user can toggle (preserves original selections)",
                verbose_name="Available Coverages",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="coverages",
            field=models.JSONField(
                default=list,
                help_text="List of currently selected coverage types",
                verbose_name="Coverages",
            ),
        ),
    ]
