# Generated by Django 5.1.4 on 2026-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0030_add_initial_ai_classifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Raw annual premium before promo code discounts. Includes 10% annual discount.",
                max_digits=15,
                null=True,
                verbose_name="Base Annual Premium",
            ),
        ),
    ]
