# Generated by Django 5.1.4 on 2026-02-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0033_backfill_wants_contractor_epli"),
    ]

    operations = [
        migrations.AlterField(
            model_name="underwriteroverride",
            name="coverage",
            field=models.CharField(
                choices=[
                    ("commercial-general-liability", "Commercial General Liability"),
                    ("media-liability", "Media Liability"),
                    ("directors-and-officers", "Directors & Officers"),
                    ("representations-warranties", "Representations & Warranties"),
                    ("technology-errors-and-omissions", "Technology E&O"),
                    ("cyber-liability", "Cyber Liability"),
                    ("fiduciary-liability", "Fiduciary Liability"),
                    ("hired-and-non-owned-auto", "Hired & Non-Owned Auto"),
                    (
                        "employment-practices-liability",
                        "Employment Practices Liability",
                    ),
                    ("claims_history", "Claims History Review"),
                    ("company", "Company Eligibility Review"),
                ],
                max_length=50,
                verbose_name="Coverage",
            ),
        ),
    ]
