# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0034_underwriter_override_company_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="business_start_date",
            field=models.DateField(
                blank=True,
                help_text="Date the business started",
                null=True,
                verbose_name="Business Start Date",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="estimated_payroll",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated annual payroll",
                max_digits=15,
                null=True,
                verbose_name="Estimated Payroll",
            ),
        ),
    ]
