# Generated by Django 5.1.4 on 2026-03-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0043_add_referral_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralpartner",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="referralpartner",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
    ]
