# Generated by Django 5.1.4 on 2026-03-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0044_fix_referral_partner_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referralpartner",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Commission percentage owed to this partner on billing premium",
                max_digits=5,
                verbose_name="Commission Rate (%)",
            ),
        ),
    ]
