# Generated by Django 5.1.4 on 2026-03-16 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0048_alter_quote_quote_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customproduct",
            options={
                "verbose_name": "Brokered Coverage",
                "verbose_name_plural": "Brokered Coverages",
            },
        ),
    ]
