# Generated by Django 5.1.4 on 2026-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0049_rename_custom_product_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralpartner",
            name="notification_emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of email addresses to notify on account creation and quote submission for this partner's referrals",
                verbose_name="Notification Emails",
            ),
        ),
    ]
