# Generated by Django 5.1.4 on 2026-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0051_add_coverage_type_and_promo_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Discount amount (percentage value like 20.00 for 20%, or fixed dollar amount)",
                max_digits=10,
                verbose_name="Discount Value",
            ),
        ),
    ]
