# Generated by Django 5.1.4 on 2026-03-30 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0052_alter_promocode_discount_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="assigned_ae",
            field=models.ForeignKey(
                blank=True,
                help_text="Account executive assigned to this quote",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned AE",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="lead_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organic", "Organic"),
                    ("referral", "Referral"),
                    ("outbound", "Outbound"),
                    ("partner", "Partner"),
                    ("paid", "Paid Ad"),
                    ("other", "Other"),
                ],
                help_text="How this lead was acquired",
                max_length=50,
                verbose_name="Lead Source",
            ),
        ),
    ]
