# Generated by Django 5.1.4 on 2026-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0056_encrypt_existing_federal_ein"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="dba_name",
            field=models.CharField(
                blank=True,
                help_text="Doing Business As (trade name), if different from legal name",
                max_length=255,
                null=True,
                verbose_name="DBA / Trade Name",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="naics_code",
            field=models.CharField(
                blank=True,
                help_text="North American Industry Classification System code",
                max_length=10,
                null=True,
                verbose_name="NAICS Code",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="naics_description",
            field=models.CharField(
                blank=True,
                help_text="Auto-filled description from NAICS code lookup",
                max_length=255,
                null=True,
                verbose_name="NAICS Description",
            ),
        ),
    ]
