# Generated by Django 5.2.13 on 2026-04-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0002_add_sharelink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharelink',
            new_name='document_sh_resourc_da8ed4_idx',
            old_name='document_sh_resourc_2b3f5e_idx',
        ),
    ]
