# Generated by Django 5.1.4 on 2026-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(
                help_text="SHA-256 hash of the raw key (plaintext is never stored)",
                max_length=64,
                verbose_name="Key Hash",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(
                help_text='Descriptive label for this key, e.g. "Agency X production"',
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="prefix",
            field=models.CharField(
                help_text="First 16 characters of the raw key, used for fast lookup",
                max_length=16,
                unique=True,
                verbose_name="Prefix",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="apikeyinvite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="apikeyinvite",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
    ]
