SECTION_LABELS = {
    "company_info": "COMPANY INFORMATION",
    "business_address": "Business Address",
    "organization_info": "Organization",
    "financial_details": "Financial Details",
    "structure_operations": "Structure & Operations",
    "commercial_general_liability": "COMMERCIAL GENERAL LIABILITY",
    "directors_officers": "DIRECTORS & OFFICERS",
    "cyber_liability": "CYBER LIABILITY",
    "tech_errors_omissions": "TECHNOLOGY ERRORS & OMISSIONS",
    "media_liability": "MEDIA LIABILITY",
    "employment_practices_liability": "EMPLOYMENT PRACTICES LIABILITY",
    "fiduciary_liability": "FIDUCIARY LIABILITY",
    "hired_non_owned_auto": "HIRED & NON-OWNED AUTO",
    "custom_commercial_auto": "COMMERCIAL AUTO",
    "custom_crime": "CRIME",
    "custom_kidnap_ransom": "KIDNAP & RANSOM",
    "custom_med_malpractice": "MEDICAL MALPRACTICE",
    "claims_history": "CLAIMS HISTORY",
    "loss_history": "Loss History",
    "insurance_history": "Insurance History",
    "limits_retentions": "LIMITS & RETENTIONS",
    "notices_signatures": "NOTICES & SIGNATURES",
    "representations_warranties": "REPRESENTATIONS & WARRANTIES",
}

FIELD_LABELS = {
    # ==================== BUSINESS ADDRESS ====================
    "street_address": "Street Address",
    "suite": "Apartment/Suite/Unit",
    "city": "City",
    "state": "State",
    "zip": "ZIP Code",
    # ==================== ORGANIZATION INFO ====================
    "entity_legal_name": "Entity Legal Name",
    "organization_type": "Organization Type",
    "organization_type_other": "Organization Type (Other)",
    "is_for_profit": "Profit Type",
    "federal_ein": "Federal EIN",
    "business_start_date": "Business Start Date",
    "estimated_payroll": "Estimated Annual Payroll ($)",
    # ==================== FINANCIAL DETAILS ====================
    "last_12_months_revenue": "Last 12 Months Revenue ($)",
    "projected_next_12_months_revenue": "Projected Next 12 Months Revenue ($)",
    "full_time_employees": "Number of Full Time Employees",
    "part_time_employees": "Number of Part Time Employees",
    "financial_statements": "Upload any financial statements if available",
    # ==================== STRUCTURE & OPERATIONS ====================
    "is_technology_company": "Is your company primarily a technology, software, or online-based business?",
    "has_subsidiaries": "Do you own any subsidiaries?",
    "all_entities_covered": "Are all entities to be covered under this application?",
    "subsidiaries_explanation": "Explain which entities are included",
    "planned_acquisitions": "Planned acquisitions, mergers or new entities in the next 12 months?",
    "planned_acquisitions_details": "Provide details",
    "business_description": "Brief Description of Business/Product",
    # ==================== COMMERCIAL GENERAL LIABILITY ====================
    # General
    "primary_operations_hazard": "Describe the nature of your operations in terms of premises and product risk (select the best fit)",
    "is_address_primary_office": "Is the business address your primary office?",
    "office_square_footage": "What is the estimated square footage of the office?",
    "has_contractual_liability": "Do your business contracts include appropriate liability waivers or limitations to manage your liability?",
    "has_other_exposures": "Are there any other aspects of your operations or activities not already described that could pose a risk of third-party bodily injury or property damage?",
    "other_exposures_description": "Describe other liability exposures",
    # Premises
    "has_physical_locations": "Does the company own, lease, or operate any locations that are not a standard office (e.g. storefront, warehouse, lab, manufacturing space, workshop)?",
    "physical_locations_description": "Describe the facilities",
    "square_footage": "Specify square footage (if known)",
    "has_safety_measures": "If you have non-office facilities or any public-facing premises, do you maintain appropriate safety measures (e.g. OSHA compliance, fire suppression systems, security protocols)?",
    "has_hazardous_materials": "Does your business use, store, or transport any hazardous materials (e.g. chemicals, flammable liquids, toxic substances)?",
    "hazardous_materials_description": "Describe the materials involved and any safety protocols or special storage/handling measures you have in place",
    # Products & Operations
    "has_products_completed_operations": "Do you have any physical products or completed operations that require coverage?",
    "products_completed_operations_description": "Please describe your product(s) or completed operations",
    "has_client_site_work": "Do your employees perform any physical work at customer locations?",
    "client_site_work_description": "Describe the nature of the on-site work and how frequently it is performed",
    "has_quality_control": "If you manufacture or sell physical products, do you have a formal product quality control or testing process?",
    "uses_subcontractors": "Do you subcontract any portion of these products or completed operations to third parties?",
    "requires_subcontractor_insurance": "Do you require subcontractors to carry their own insurance and sign contracts indemnifying your company?",
    # ==================== DIRECTORS & OFFICERS ====================
    # Governance
    "is_publicly_traded": "Is the company publicly traded or does it plan an initial public offering (IPO) of securities within the next 12 months?",
    "public_offering_details": "Describe public offering details",
    "has_mergers_acquisitions": "Has the company been involved in any merger or acquisition in the past 3 years, or does it anticipate any such transaction in the next 12 months?",
    "mergers_acquisitions_details": "Provide merger/acquisition details",
    "board_size": "Directors on the company's Board",
    "independent_directors": "Independent (non-employee) directors",
    "director_names": "Provide the names of all directors",
    "has_board_meetings": "Does the Board of Directors meet at least quarterly and maintain written minutes of meetings?",
    # Financials
    "funding_raised": "Total amount raised",
    "funding_date": "Funding date",
    "has_financial_audits": "Are the company's financial statements audited or reviewed by an external CPA firm at least annually?",
    "has_legal_compliance_officer": "Does the company have an in-house general counsel or compliance officer (or equivalent role)?",
    "is_profitable": "Was the company profitable in the most recent fiscal year?",
    "has_indebtedness": "Does the company have any outstanding loans or lines of credit?",
    "has_breached_loan_covenants": "Has it breached any loan covenants in the past 12 months?",
    # ==================== CYBER LIABILITY ====================
    # Risk & Security
    "data_systems_exposure": "Data & Systems Exposure (Check any that apply)",
    "employee_band": "Total number of network users/employees",
    "sensitive_record_count": "How many records containing sensitive personal or confidential data does the company store or process?",
    "all_users_have_unique_logins": "Do all users have unique logins and follow basic security practices?",
    "security_controls": "Does the company implement the following cybersecurity measures? (Check all that apply)",
    "security_framework_certified": "Is the company currently certified or attested to a recognized security framework (SOC 2 Type II, ISO 27001, or equivalent)?",
    "regulatory_sublimit": "Optional Regulatory Actions sublimit?",
    # Compliance
    "outsources_it": "Do you rely on third-party vendors to host or process your data?",
    "requires_vendor_security": "Do your contracts with those vendors require them to follow security standards or take responsibility for data breaches?",
    "has_past_incidents": "Has the company experienced any data breach, cyber attack, or major network outage in the past 5 years?",
    "incident_details": "Provide details (including whether any sensitive data was compromised and any remediation)",
    "regulations_subject_to": "What data security/privacy regulations are you subject to?",
    "wants_hipaa_penalties_coverage": "Would you like to add coverage for HIPAA penalties?",
    "maintained_compliance": "Have you ever been fined or penalized for violating a data privacy or security regulation?",
    "compliance_issues_description": "Please explain compliance issues",
    # ==================== TECHNOLOGY ERRORS & OMISSIONS ====================
    # Product Details
    "services_description": "Please describe the technology products and services that you provide",
    "service_criticality": "How critical is your product/service to your customers' operations or safety?",
    "industry_hazards": "Does the company's technology operate in any high-risk or regulated domains?",
    # Risk Assessment
    "has_liability_protections": "Do your standard client contracts include liability limitations or warranty disclaimers?",
    "has_quality_assurance": "Do you have a formal testing and QA process before release?",
    "has_prior_incidents": "Has the company ever experienced a significant product failure that caused financial harm to a client?",
    # incident_details already defined in cyber
    # AI Coverage
    "uses_ai": "Do you use artificial intelligence or machine learning in your products, services, or internal operations?",
    "wants_ai_coverage": "Would you like to add optional coverage for AI-related risks?",
    "ai_coverage_options": "Selected AI coverage options",
    # ==================== MEDIA LIABILITY ====================
    # Content Operations
    "has_media_exposure": "Does your company engage in publishing content (beyond standard marketing)?",
    "media_content_types": "What types of content or platforms? (Check all that apply)",
    "original_content_volume": "Original company-produced posts/articles",
    "ugc_content_volume": "User-generated posts/comments (if any)",
    "has_content_moderation": "If your platform/app includes user content, do you moderate or review user submissions (at least periodically) before or after they go live?",
    "moderation_details": "Describe moderation level",
    # Content Risk
    "has_media_controls": "Do you have procedures to screen content for libel, copyright or trademark infringement, or privacy issues before publication?",
    "has_past_complaints": "Have you ever received any legal complaints or demands alleging defamation, infringement, or other wrongdoing in your published content?",
    "past_complaint_details": "Please describe the situation and resolution",
    "uses_third_party_content": "Do you use third-party content (images, music, code, etc.) in your materials?",
    "has_licenses": "Do you ensure you have the proper licenses or permissions for all such content?",
    # ==================== EMPLOYMENT PRACTICES LIABILITY ====================
    # Workforce Info
    "total_employees_us": "Total number of employees in the U.S.",
    "employees_outside_us": "If the company has employees outside the U.S., list count and countries",
    "geographic_spread": "Geographic Spread - List all states the company has employees in, and how many work in each state",
    "average_salary_level": "What is the approximate average annual salary of your employees?",
    "uses_contractors": "Do you have any independent contractors?",
    "wants_contractor_epli": "Since you use contractors, do you want EPLI protection if a contractor alleges harassment, discrimination, or wrongful termination?",
    "contractor_geographic_spread": "Contractor Geographic Spread - List all states where contractors are located, and how many in each state",
    "contractor_international_spread": "International Contractors - List all countries outside the U.S. where you have contractors, and how many in each country",
    # HR Practices
    "has_past_layoffs": "Past 12 months: Have there been any layoffs, redundancies, or terminations affecting over 10% of the workforce?",
    "past_layoff_details": "Please describe (include approximately what percentage of employees were laid off)",
    "has_planned_layoffs": "Next 12 months: Are any layoffs or reorganizations planned?",
    "planned_layoff_details": "Describe anticipated scope",
    "hr_policies": "HR Policies & Training: Check if any of the following apply",
    "has_hourly_employees": "Does the company have hourly (non-exempt) employees?",
    "is_wage_compliant": "Are timekeeping, overtime, and meal/rest break practices compliant with applicable wage laws (to the best of your knowledge)?",
    "has_third_party_interaction": "Do any employees regularly interact with clients, customers, or vendors as part of their job duties?",
    "has_third_party_training": "Do you provide training on appropriate conduct with third parties?",
    # ==================== FIDUCIARY LIABILITY ====================
    # Plan Details
    "benefit_plan_types": "Employee benefit plans the company offers",
    "benefit_plan_other_description": "Other benefit plan description",
    "total_plan_assets": "Total assets under management for all ERISA benefit plans",
    "has_defined_benefit_plan": "Does the company sponsor any defined benefit (DB) pension plan?",
    "defined_benefit_funding_percent": "Approximate current funding percentage of the plan",
    "has_company_stock_in_plan": "Do any plans hold company stock or have an ESOP?",
    "company_stock_details": "Provide details (% of plan assets in employer securities)",
    # Service Providers
    "recordkeeper": "Recordkeeper/Administrator",
    "third_party_admin": "Third-Party Administrator (TPA)",
    "custodian": "Custodian/Trustee (for plan assets)",
    "investment_advisor": "Investment Advisor or Consultant",
    "benefits_broker": "Benefits Broker/Advisor",
    "actuary": "Actuary (if any for pension plans)",
    "has_written_agreements": "Are written agreements in place with all the above service providers?",
    "review_frequency": "How often do you formally review the performance and fees of these service providers?",
    "review_frequency_other": "Please specify review frequency",
    # Controls
    "has_regulatory_issues": "Any regulatory compliance issues or corrections (e.g. filings under IRS/DOL correction programs, late remittance of contributions)?",
    "has_significant_changes": "Any significant plan changes such as mergers, terminations, or large amendments to benefits or plan structure?",
    # compliance_issues_description already defined in cyber
    "has_fiduciary_committee": "Is there a designated committee or individual responsible for overseeing benefit plan administration and investments (fiduciary committee)?",
    "has_fiduciary_training": "Do plan fiduciaries receive regular training or professional guidance on their responsibilities?",
    "has_past_claims": "Have any claims, lawsuits, or official inquiries been made in the past 5 years?",
    "past_claims_details": "Please provide claim details",
    # ==================== HIRED & NON-OWNED AUTO ====================
    # Driver Info
    "driver_band": "Approximately how many employees (or principals) use their personal or rented vehicles for company business on a regular basis?",
    "has_drivers_under_25": "Will any of them be under the age of 25?",
    "driving_frequency": "How frequently do these individuals drive for business purposes?",
    "travel_distance": "Are business-related drives generally local or do they include long-distance?",
    "has_driver_safety_measures": "Does the company have any policies or programs to promote safe driving by employees (e.g. cellphone policy, MVR checks)?",
    # Vehicle History
    "rents_vehicles": "Does the company ever rent or hire vehicles for business use?",
    "rental_vehicle_details": "How often and what types of vehicles?",
    "has_high_value_vehicles": "Does business use involve any high-value or specialty vehicles or driving outside the U.S. (e.g. luxury cars, trucks, or international driving)?",
    "high_value_vehicle_details": "Please describe high-value vehicle usage",
    "has_past_auto_incidents": "Has the company had any auto-related incidents or losses in the past 5 years?",
    "past_auto_incident_details": "Provide details (include any accidents involving employees on company business)",
    "vin": "Vehicle Identification Number (VIN)",
    "body_category": "Body Category",
    "year": "Year",
    "make": "Make",
    "model": "Model",
    "estimated_value": "Estimated Value ($)",
    "vehicle_radius": "Vehicle Operating Radius (miles)",
    "number_of_drivers": "Number of Drivers",
    # ==================== CRIME INSURANCE ====================
    "hiring_process_checks": "Hiring process checks",
    "segregation_cash_receipts": "Are different employees responsible for handling and recording cash?",
    "cash_quantity": "Cash Quantity",
    "has_crime_losses": "Has the applicant incurred any crime or kidnap and ransom related losses or incidents during the past 3 years?",
    "separate_check_signer": "Does someone other than the person responsible for reconciling bank accounts sign checks?",
    "countersign_procedure": "Does the applicant have a procedure where all checks need to be countersigned?",
    "property_credit_card_receipts": "Value of credit card receipts kept on site ($)",
    "property_retail_checks": "Value of checks kept on site (if accepted) ($)",
    "authority_separated": "Is the authority to initiate and approve amounts separated amongst different employees?",
    "segregation_areas": "Select areas with split responsibilities across employees",
    "segregation_inventory_management": "Is segregation of duties practiced for inventory management?",
    "special_exposures": "Special exposures that apply",
    "inventory_computerized": "Are inventory records computerized?",
    "physical_inventory_count_annual": "Does the applicant perform a physical count of inventory at least on an annual basis?",
    "software_fraud_detection": "Is there software security in place to detect fraudulent computer usage by employees, agents and outsiders?",
    "edp_authorized_documented": "Are your electronic data processing (EDP) systems and any changes to them authorized, documented, and tested?",
    "incoming_checks_stamped_deposit_only": "Are all incoming checks stamped 'for deposit only' immediately upon receipt?",
    "separate_deposit_person": "Is the person who makes deposits different from the person who reconciles bank accounts?",
    "separate_withdrawal_person": "Is the person who makes withdrawals different from the person who reconciles bank accounts?",
    "passwords_changed_regularly": "Are passwords and access codes changed at regular intervals and when users are terminated?",
    "employees_travel_outside_us_canada": "Do directors, officers, or other employees take trips outside the United States and Canada?",
    "foreign_trips_planned": "Planned foreign trips in the next 12 months",
    "safety_procedures_changed_past_12mo": "Has the applicant materially changed its safety procedures for employee travel outside the United States in the past 12 months?",
    "safety_procedures_explanation": "Explanation of safety procedure changes",
    "safety_steps_for_international_travel": "Are steps taken to ensure an insured person's safety when they travel outside the United States?",
    "safety_steps_travel_explanation": "Safety steps for international travel",
    "safety_steps_for_permanent_foreign_locations": "Are steps taken to ensure the safety of insured persons and premises permanently located outside of the United States?",
    "safety_steps_foreign_explanation": "Safety steps for permanent foreign locations",
    "permanent_foreign_locations": "Permanent foreign locations outside the United States and Canada",
    "operates_ships_vessels": "Does the applicant own or operate, or know of persons who will work or travel on any ships, vessels, tugs, barges, or rigs?",
    "foodstuffs_beverages_pharmaceuticals": "Are any of your operations involved in producing food, beverages, or pharmaceuticals?",
    "foodstuffs_explanation": "Description of foodstuffs, beverages, or pharmaceutical operations",
    # ==================== MEDICAL MALPRACTICE ====================
    "insurance_start_date": "When would you like group insurance to start?",
    "practice_type": "What type of practice do you have?",
    "group_practicing_year": "Has your group been practicing together for at least a year?",
    "policy_type": "What type of policy would you like?",
    "correctional_facility_services": "Does your group provide services for or at a correctional facility?",
    "special_services": "Does your group provide any of the following treatments or services?",
    "special_services_other": "Other treatments or services description",
    "known_claims_explanation": "Description of known claims circumstances",
    "cosmetic_aesthetics_procedures": "Does your group perform cosmetic or medical aesthetics procedures?",
    "prescribes_controlled_substances": "Does any member of your group prescribe controlled substances?",
    "known_claims_circumstances": "Do you have knowledge of any circumstance, allegation or incident that could result in any claim, suit or complaint being brought against your group?",
    # ==================== LOSS HISTORY ====================
    # has_past_claims already defined
    "claim_details": "Please provide details (date, allegations, amount paid/reserved, status)",
    "claim_documents": "Supporting Documents",
    "has_known_circumstances": "Is the Applicant aware of any fact, circumstance, or situation that has not yet resulted in a formal claim but could reasonably be expected to give rise to a claim?",
    "known_circumstances_details": "Provide details of each such situation",
    # ==================== INSURANCE HISTORY ====================
    "has_prior_coverage": "Has the company carried any of the selected lines of insurance in the past?",
    "prior_coverage_details": "List the coverage and insurer (and retroactive date, if claims-made)",
    "has_refused_insurance": "Has any insurance company ever declined, canceled, or non-renewed any similar insurance policy for the Applicant?",
    "refused_insurance_details": "Please explain the circumstances (which coverage, when, and reason if known)",
    # ==================== NOTICES & SIGNATURES ====================
    "agreed_to_terms": "Agreed to Terms and Conditions",
    "applicant_name": "Applicant Name",
    "applicant_date": "Policy Effective Date",
    # ==================== REPRESENTATIONS & WARRANTIES ====================
    # Transaction Details
    "transaction_documents": "Please attach the full transaction agreement and any material accompanying documents",
    "transaction_value": "Approximate transaction value (purchase price)",
    "transaction_role": "The insured is the Buyer or Seller for this transaction?",
    "target_company_description": "Briefly describe the target company or business being sold/purchased (industry, operations)",
    "has_known_issues": "Any known issues in the target's history (e.g. past lawsuits, regulatory problems)?",
    "known_issues_description": "Please describe known issues",
    # Diligence & Deal Terms
    "due_diligence_level": "Due Diligence Conducted",
    "disclosure_level": "Disclosure of Issues",
    "deal_terms_tilt": "Deal Terms Tilt",
    # Liability & Indemnity
    "has_seller_indemnity": "Does the purchase agreement include a seller indemnity for breaches of reps & warranties (outside of the insurance policy)?",
    "reps_survival_months": "What is the general survival period for representations in the purchase contract (for non-fundamental reps)?",
    "has_contingent_liabilities": "Were there any known issues identified during due diligence that will likely be excluded from coverage or addressed via escrow/special indemnity?",
    "contingent_liabilities_description": "Briefly describe contingent liabilities",
    "has_prior_litigation": "Are you aware of any past or pending litigation or regulatory actions involving the target company that were not fully resolved prior to this transaction?",
    "prior_litigation_details": "Detail any such matters",
    # ==================== LIMITS & RETENTIONS ====================
    "aggregate_limit": "Aggregate Limit",
    "per_occurrence_limit": "Per Occurrence Limit",
    "retention": "Retention/Deductible",
}

VALUE_DISPLAY = {
    True: "Yes",
    False: "No",
    "for-profit": "For Profit",
    "not-for-profit": "Not For Profit",
    "individual": "Individual",
    "partnership": "Partnership",
    "corporation": "Corporation",
    "llc": "LLC",
    "other": "Other",
    # CGL Hazard Levels
    "low-hazard": "Low Hazard - Office/professional services only",
    "elevated-hazard": "Elevated Hazard - Some physical products or on-site operations",
    "high-hazard": "High Hazard - Manufacturing, construction, or high-risk operations",
    # Square Footage
    "up_to_2500": "Up to 2,500 sq ft",
    "2501_5000": "2,501 - 5,000 sq ft",
    "5001_10000": "5,001 - 10,000 sq ft",
    "10001_25000": "10,001 - 25,000 sq ft",
    "over_25000": "Over 25,000 sq ft",
    # Billing
    "annual": "Annual",
    "monthly": "Monthly",
    # Yes/No/NA
    "Yes": "Yes",
    "No": "No",
    "N/A": "N/A",
    # Cyber Employee Bands
    "under_25": "Under 25",
    "25_50": "25-50",
    "50_250": "50-250",
    "250_500": "250-500",
    "500_1000": "500-1,000",
    "over_1000": "Over 1,000",
    # Cyber Sensitive Record Count
    "under_10k": "Under 10,000",
    "10k_100k": "10,000-100,000",
    "100k_1m": "100,000-1,000,000",
    "over_1m": "Over 1,000,000",
    # Security Framework
    "yes": "Yes - Currently certified",
    "in-progress": "In Progress",
    "no": "No",
    # Regulatory Sublimits
    "0": "0% (No sublimit)",
    "5": "5%",
    "10": "10%",
    "25": "25%",
    "50": "50%",
    "100": "100% (Full limit)",
    # Tech E&O Criticality
    "low": "Low - Convenience or efficiency tool",
    "medium": "Medium - Important but not essential",
    "high": "High - Critical to operations",
    "mission-critical": "Mission Critical - Safety or life-critical systems",
    "not-critical": "Not Critical - Failure would cause minimal disruption",
    "moderately-critical": "Moderately Critical - Failure could cause notable disruption",
    "highly-critical": "Highly Critical - Failure could cause significant financial losses or safety issues",
    # AI Coverage Options
    "algorithmic-bias-liability": "Algorithmic Bias Liability",
    "ai-intellectual-property-liability": "AI Intellectual Property Liability",
    "regulatory-investigation-defense-costs": "Regulatory Investigation Defense Costs",
    "hallucination-defamation-liability": "Hallucination / Defamation Liability",
    "training-data-misuse-liability": "Training-Data Misuse Liability",
    "data-poisoning-adversarial-attack": "Data Poisoning / Adversarial Attack",
    "service-interruption-liability": "Service Interruption Liability",
    "bodily-injury-property-damage-autonomous-ai": "Bodily Injury / Property Damage from Autonomous AI",
    "deepfake-synthetic-media-liability": "Deepfake & Synthetic Media Liability",
    "civil-fines-penalties": "Civil Fines & Penalties (where insurable)",
    "cars-pickup-suv": "Cars / Pickup / SUV",
    "trucks": "Trucks",
    "vans": "Vans",
    "trailer": "Trailer",
    "0-50": "0 - 50 miles",
    "51-100": "51 - 100 miles",
    "201-499": "201 - 499 miles",
    "500-999": "500 - 999 miles",
    "1000-plus": "1,000+ miles",
    # Med malpractice policy types
    "claims-made": "Claims-Made",
    "occurrence": "Occurrence",
    # Med malpractice special services
    "elective-hormone-therapy": "Elective hormone therapy",
    "elective-iv-hydration-vitamin": "Elective IV hydration/vitamin injections",
    "ketamine-injections-psychiatric": "Ketamine injections for psychiatric disorders outside supervised clinical setting",
    "stem-cells-injections": "Stem cells injections",
    # Crime hiring checks
    "prior-employment-verification": "Prior employment verification",
    "drug-testing": "Drug testing",
    "education-verification": "Education verification",
    "credit-history": "Credit history",
    "criminal-history": "Criminal history",
    # Crime segregation areas
    "blank-checks-oversight": "Oversight of blank checks stock",
    "purchase-order-approval": "Purchase order approval and payment",
    "vendor-approval": "Vendor approval",
    "precious-metals": "Precious metals",
    "warehousing": "Warehousing",
    "managed-assets": "Managed assets",
    "high-unit-portable-inventory": "High-unit portable inventory",
    "care-custody-client-property": "Care/custody of client property",
    # HNOA Driver Bands
    "1_2": "1-2 drivers",
    "0_5": "0-5 drivers",
    "6_10": "6-10 drivers",
    "11_25": "11-25 drivers",
    "26_50": "26-50 drivers",
    "over_50": "Over 50 drivers",
    # HNOA Driving Frequency
    "rarely": "Rarely (a few times per year)",
    "occasionally": "Occasionally (a few times per month)",
    "frequently": "Frequently (weekly or more)",
    "daily": "Daily",
    # HNOA Travel Distance
    "local": "Local (within city/metro area)",
    "regional": "Regional (within state/region)",
    "national": "National (cross-country)",
    "international": "International",
    # EPL Salary Levels
    "under_50k": "Under $50,000",
    "50k_100k": "$50,000-$100,000",
    "100k_200k": "$100,000-$200,000",
    "over_200k": "Over $200,000",
    # Fiduciary Plan Assets
    "under_1m": "Under $1 million",
    "1m_5m": "$1-5 million",
    "5m_10m": "$5-10 million",
    "10m_25m": "$10-25 million",
    "25m_50m": "$25-50 million",
    "50m_100m": "$50-100 million",
    "over_100m": "Over $100 million",
    # Fiduciary Review Frequency
    "annually": "Annually",
    "every_2_years": "Every 2 years",
    "every_3_years": "Every 3 years",
    "as_needed": "As needed/ad-hoc",
    # R&W Transaction Role
    "buyer": "Buyer",
    "seller": "Seller",
    # R&W Due Diligence Level
    "comprehensive": "Comprehensive - Full legal, financial, and operational review",
    "standard": "Standard - Typical due diligence process",
    "limited": "Limited - Basic review only",
    # R&W Disclosure Level
    "full": "Full - All material issues disclosed",
    "partial": "Partial - Some issues disclosed",
    "minimal": "Minimal - Limited disclosure",
    # R&W Deal Terms Tilt
    "buyer_favorable": "Buyer Favorable",
    "balanced": "Balanced",
    "seller_favorable": "Seller Favorable",
}

COVERAGE_DISPLAY_NAMES = {
    "commercial-general-liability": "Commercial General Liability (CGL)",
    "cyber-liability": "Cyber Liability",
    "directors-and-officers": "Directors & Officers (D&O)",
    "employment-practices-liability": "Employment Practices Liability (EPL)",
    "fiduciary-liability": "Fiduciary Liability",
    "hired-and-non-owned-auto": "Hired & Non-Owned Auto (HNOA)",
    "custom-commercial-auto": "Commercial Auto",
    "custom-crime": "Crime Insurance",
    "custom-fidelity": "Fidelity Bond",
    "custom-kidnap-ransom": "Kidnap & Ransom",
    "custom-med-malpractice": "Medical Malpractice",
    "custom-workers-comp": "Workers Compensation",
    "custom-bop": "Business Owners Policy",
    "custom-umbrella": "Umbrella",
    "custom-excess-liability": "Excess Liability",
    "media-liability": "Media Liability",
    "technology-errors-and-omissions": "Tech E&O",
}
