# Generated by Django 5.1.4 on 2026-03-28 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_add_notification_and_audit_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_log_e_user_id_5910c5_idx",
            old_name="audit_log_user_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_log_e_model_n_ee794a_idx",
            old_name="audit_log_model_object_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_611c58_idx",
            old_name="notificatio_user_id_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_6c7360_idx",
            old_name="notificatio_user_id_read_at_idx",
        ),
    ]
