# Generated by Django 5.1.4 on 2026-03-31 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common",
            "0002_rename_audit_log_user_timestamp_idx_audit_log_e_user_id_5910c5_idx_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeToSignRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "signed_name",
                    models.CharField(
                        help_text="The full name typed by the signer as their electronic signature.",
                        max_length=255,
                        verbose_name="Signed Name",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the signer at time of signing.",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Browser/client user agent string at time of signing.",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "signed_object_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="PK of the model instance being signed.",
                        null=True,
                        verbose_name="Signed Object ID",
                    ),
                ),
                (
                    "agreement_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the agreement text presented at signing.",
                        verbose_name="Agreement Text",
                    ),
                ),
                (
                    "signed_content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="ContentType of the model being signed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Signed Document Type",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user who signed, if available.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signatures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature Record",
                "verbose_name_plural": "Signature Records",
                "db_table": "type_to_sign_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
