# Generated by Django 5.1.4 on 2026-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_add_type_to_sign_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short description of the compliance obligation",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date by which the obligation must be completed",
                        verbose_name="Deadline Date",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("license_renewal", "License Renewal"),
                            ("carrier_filing", "Carrier Filing"),
                            ("regulatory", "Regulatory"),
                            ("audit", "Audit"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        help_text="Name or email of the person responsible for completing this task",
                        max_length=255,
                        verbose_name="Responsible Person",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Full description, instructions, or reference links",
                        verbose_name="Description",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes or progress updates",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this deadline was marked as completed",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "alert_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the last compliance alert was sent for this deadline",
                        null=True,
                        verbose_name="Alert Sent At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Deadline",
                "verbose_name_plural": "Compliance Deadlines",
                "db_table": "compliance_deadlines",
                "ordering": ["deadline_date", "type"],
                "indexes": [
                    models.Index(
                        fields=["status", "deadline_date"],
                        name="compliance__status_c93b90_idx",
                    ),
                    models.Index(
                        fields=["type", "deadline_date"],
                        name="compliance__type_7d2c1f_idx",
                    ),
                ],
            },
        ),
    ]
