# Generated by Django 5.1.4 on 2026-03-31 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_add_data_access_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dataaccesslog",
            new_name="data_access_user_id_2940f1_idx",
            old_name="data_access_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="dataaccesslog",
            new_name="data_access_model_n_90d7ba_idx",
            old_name="data_access_model_obj_idx",
        ),
        migrations.RenameIndex(
            model_name="dataaccesslog",
            new_name="data_access_action_ce5fb0_idx",
            old_name="data_access_action_ts_idx",
        ),
    ]
