# Generated by Django 5.1.4 on 2026-03-31 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_feature_flags"),
        (
            "common",
            "0006_rename_data_access_user_ts_idx_data_access_user_id_2940f1_idx_and_more",
        ),
    ]

    operations = []
