# Generated by Django 5.1.4 on 2026-03-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_merge_20260331_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
    ]
