# Generated by Django 5.1.4 on 2026-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_alter_featureflag_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier, e.g. 'limit_options', 'carrier_list'",
                        max_length=100,
                        unique=True,
                        verbose_name="Config Key",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="JSON value — array, object, number, or string",
                        verbose_name="Value (JSON)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("underwriting", "Underwriting"),
                            ("brokerage", "Brokerage"),
                            ("billing", "Billing & Fees"),
                            ("carriers", "Carriers"),
                            ("coverages", "Coverages"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of what this config controls",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Config",
                "verbose_name_plural": "Platform Config",
                "db_table": "platform_config",
                "ordering": ["category", "key"],
            },
        ),
    ]
