# Generated by Django 5.1.4 on 2026-01-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quotes", "0002_change_protect_to_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid",
                        max_digits=15,
                        verbose_name="Premium",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                ("expiration_date", models.DateField(verbose_name="Expiration Date")),
                ("purchased_at", models.DateTimeField(verbose_name="Purchased At")),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase",
                        to="quotes.quote",
                        verbose_name="Quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
                "db_table": "purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text="Type/category of document (e.g., proof-of-insurance)",
                        max_length=50,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        help_text="Size in bytes", verbose_name="File Size"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME Type"),
                ),
                ("s3_key", models.CharField(max_length=500, verbose_name="S3 Key")),
                ("s3_url", models.URLField(max_length=1000, verbose_name="S3 URL")),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="policies.purchase",
                        verbose_name="Purchase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Document",
                "verbose_name_plural": "Purchase Documents",
                "db_table": "purchase_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
