# Generated by Django 5.1.4 on 2026-01-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0003_rename_purchase_to_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="billing_frequency",
            field=models.CharField(
                choices=[("annual", "Annual"), ("monthly", "Monthly")],
                default="annual",
                help_text="Payment frequency (annual or monthly)",
                max_length=10,
                verbose_name="Billing Frequency",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="monthly_premium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly payment amount (annual premium / 12)",
                max_digits=15,
                null=True,
                verbose_name="Monthly Premium",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe customer ID for subscription management",
                max_length=255,
                null=True,
                verbose_name="Stripe Customer ID",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe subscription ID for monthly billing",
                max_length=255,
                null=True,
                verbose_name="Stripe Subscription ID",
            ),
        ),
    ]
