# Generated by Django 5.1.4 on 2026-01-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0008_policy_carrier_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="carrier",
            field=models.CharField(
                default="Technology Risk Retention Group, Inc.",
                help_text="Insurance carrier name",
                max_length=255,
                verbose_name="Carrier",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Stripe Invoice ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount"
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Status")),
                ("paid_at", models.DateTimeField(verbose_name="Paid At")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-paid_at"],
            },
        ),
    ]
