# Generated by Django 5.1.4 on 2026-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0009_add_payment_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policysequence",
            name="lob_code",
            field=models.CharField(max_length=3),
        ),
    ]
