# Generated by Django 5.1.4 on 2026-01-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0010_expand_lob_code_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount percentage applied (e.g., 20.00 for 20%)",
                max_digits=5,
                null=True,
                verbose_name="Discount Percentage",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="promo_code",
            field=models.CharField(
                blank=True,
                help_text="Promo code applied at purchase",
                max_length=50,
                null=True,
                verbose_name="Promo Code",
            ),
        ),
    ]
