# Generated by Django 5.1.4 on 2026-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0011_add_discount_tracking_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="premium",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Actual premium paid after all discounts applied",
                max_digits=15,
                verbose_name="Premium",
            ),
        ),
    ]
