# Generated by Django - replaced with management command
# Original migration called Stripe API which fails during deployment
# Run: python manage.py backfill_stripe_customer_ids

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0013_refactor_payment_stripe_id"),
    ]

    operations = [
        # No-op: backfill is now done via management command or admin UI
        # /admin/policies/policy/backfill-customer-ids/
    ]
