from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0017_fix_allocation_percent_scale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("non_renewed", "Non-renewed"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="insured_legal_name",
            field=models.CharField(
                blank=True,
                help_text="Legal name of the insured entity",
                max_length=255,
                null=True,
                verbose_name="Insured Legal Name",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="insured_fein",
            field=models.CharField(
                blank=True,
                help_text="Federal Employer Identification Number of the insured",
                max_length=20,
                null=True,
                verbose_name="Insured FEIN",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="mailing_address",
            field=models.JSONField(
                blank=True,
                help_text="Insured mailing address {street, suite, city, state, zip}",
                null=True,
                verbose_name="Mailing Address",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="principal_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                    ("DC", "District of Columbia"),
                    ("AS", "American Samoa"),
                    ("GU", "Guam"),
                    ("MP", "Northern Mariana Islands"),
                    ("PR", "Puerto Rico"),
                    ("VI", "Virgin Islands"),
                ],
                help_text="Primary state of the insured",
                max_length=2,
                null=True,
                verbose_name="Principal State",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="paid_to_date",
            field=models.DateField(
                blank=True,
                help_text="Date through which premium has been paid",
                null=True,
                verbose_name="Paid-to Date",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="producer_id",
            field=models.CharField(
                blank=True,
                help_text="External producer/agent identifier",
                max_length=50,
                null=True,
                verbose_name="Producer ID",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="producer_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the producing agent/broker",
                max_length=255,
                null=True,
                verbose_name="Producer Name",
            ),
        ),
    ]
