# Generated by Django 5.1.4 on 2026-02-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0019_backfill_policy_regulatory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="policytransaction",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Human-readable description of what changed",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policytransaction",
            name="accounting_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="policytransaction",
            name="effective_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="policytransaction",
            name="gross_written_premium",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="policytransaction",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="policies.policy",
            ),
        ),
        migrations.AlterField(
            model_name="policytransaction",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="policytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("new", "New Business"),
                    ("renewal", "Renewal"),
                    ("endorsement", "Endorsement"),
                    ("cancel", "Cancellation"),
                    ("reinstate", "Reinstatement"),
                    ("audit", "Audit"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stateallocation",
            name="allocated_premium",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name="stateallocation",
            name="allocation_method",
            field=models.CharField(
                choices=[
                    ("hq", "Headquarters"),
                    ("payroll", "Payroll"),
                    ("headcount", "Headcount"),
                    ("revenue", "Revenue"),
                    ("location_schedule", "Location Schedule"),
                ],
                default="hq",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stateallocation",
            name="state",
            field=models.CharField(
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                    ("DC", "District of Columbia"),
                    ("AS", "American Samoa"),
                    ("GU", "Guam"),
                    ("MP", "Northern Mariana Islands"),
                    ("PR", "Puerto Rico"),
                    ("VI", "Virgin Islands"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="stateallocation",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_allocations",
                to="policies.policytransaction",
            ),
        ),
    ]
