# Generated by Django 5.1.4 on 2026-02-09 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0020_add_description_to_policytransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="producer_id",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="producer_name",
        ),
        migrations.CreateModel(
            name="Cession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "treaty_id",
                    models.CharField(max_length=50, verbose_name="Treaty ID"),
                ),
                (
                    "reinsurance_type",
                    models.CharField(
                        choices=[("XOL", "Excess of Loss"), ("QS", "Quota Share")],
                        max_length=3,
                        verbose_name="Reinsurance Type",
                    ),
                ),
                (
                    "attachment_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Attachment Point"
                    ),
                ),
                (
                    "ceded_premium_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Ceded Premium Rate",
                    ),
                ),
                (
                    "ceded_premium_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Ceded Premium Amount",
                    ),
                ),
                (
                    "reinsurer_name",
                    models.CharField(max_length=100, verbose_name="Reinsurer Name"),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cessions",
                        to="policies.policytransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cession",
                "verbose_name_plural": "Cessions",
                "db_table": "cessions",
                "unique_together": {("transaction", "treaty_id")},
            },
        ),
    ]
