# Generated by Django 5.1.4 on 2026-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0022_normalize_payment_status_succeeded_to_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="monthly_premium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly payment amount billed to the customer",
                max_digits=15,
                null=True,
                verbose_name="Monthly Premium",
            ),
        ),
    ]
