# Generated by Django 5.1.4 on 2026-02-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0023_alter_policy_monthly_premium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("non_renewed", "Non-renewed"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
