# Generated by Django 5.1.4 on 2026-03-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0025_add_renewal_fields_and_policy_renewal"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="aggregate_limit",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum total payout for the policy period",
                null=True,
                verbose_name="Aggregate Limit",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="per_occurrence_limit",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum payout per single occurrence/claim",
                null=True,
                verbose_name="Per Occurrence Limit",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="retention",
            field=models.IntegerField(
                blank=True,
                help_text="Amount the insured pays before coverage kicks in",
                null=True,
                verbose_name="Retention / Deductible",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="limits_retentions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Legacy JSON blob — use the dedicated fields below instead",
                verbose_name="Limits & Retentions (legacy)",
            ),
        ),
    ]
