# Generated by Django 5.1.4 on 2026-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0026_add_separate_limit_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="carrier",
            field=models.CharField(
                db_index=True,
                default="Technology Risk Retention Group, Inc.",
                help_text="Insurance carrier name",
                max_length=255,
                verbose_name="Carrier",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="coi_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Certificate of Insurance number shared by policies from same purchase",
                max_length=20,
                null=True,
                verbose_name="COI Number",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="coverage_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="The specific coverage type for this policy",
                max_length=50,
                verbose_name="Coverage Type",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="expiration_date",
            field=models.DateField(db_index=True, verbose_name="Expiration Date"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("non_renewed", "Non-renewed"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
