# Generated by Django 5.1.4 on 2026-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0028_add_soft_delete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="continuity_date",
            field=models.DateField(
                blank=True,
                help_text="Date of continuous coverage with prior carrier. Used to determine whether retroactive date credit is available.",
                null=True,
                verbose_name="Continuity Date",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="extended_reporting_period_months",
            field=models.IntegerField(
                blank=True,
                help_text="Duration of the tail coverage / ERP in months after policy expiration. Common values: 12, 24, 36, 60, 84 (unlimited = 999).",
                null=True,
                verbose_name="Extended Reporting Period (months)",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="prior_pending_litigation_date",
            field=models.DateField(
                blank=True,
                help_text="Cut-off date for prior and pending litigation exclusion. Claims or circumstances known before this date are excluded.",
                null=True,
                verbose_name="Prior & Pending Litigation Date",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="retroactive_date",
            field=models.DateField(
                blank=True,
                help_text="Date from which prior acts are covered (claims-made basis). Typically set to the first inception date of continuous coverage.",
                null=True,
                verbose_name="Retroactive Date",
            ),
        ),
    ]
