# Generated by Django 5.1.4 on 2026-03-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0029_policy_continuity_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="force_ntic",
            field=models.BooleanField(
                default=False,
                help_text="Override: force this policy to use NTIC carrier regardless of limit threshold. Use when NTIC is required below the $2M auto-trigger (e.g. manuscript endorsement).",
                verbose_name="Force NTIC Carrier",
            ),
        ),
    ]
