# Generated by Django 5.1.4 on 2026-03-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0030_policy_force_ntic"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyExcessLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "primary_carrier",
                    models.CharField(
                        help_text="Name of the primary/fronting carrier (e.g. Travelers, Markel)",
                        max_length=255,
                        verbose_name="Primary Carrier",
                    ),
                ),
                (
                    "primary_carrier_naic",
                    models.CharField(
                        blank=True,
                        help_text="NAIC code of the primary carrier",
                        max_length=20,
                        null=True,
                        verbose_name="Primary Carrier NAIC",
                    ),
                ),
                (
                    "primary_policy_number",
                    models.CharField(
                        blank=True,
                        help_text="Policy number issued by the primary carrier",
                        max_length=50,
                        null=True,
                        verbose_name="Primary Policy Number",
                    ),
                ),
                (
                    "primary_limit",
                    models.IntegerField(
                        help_text="Primary layer aggregate limit in dollars",
                        verbose_name="Primary Limit",
                    ),
                ),
                (
                    "primary_retention",
                    models.IntegerField(
                        default=0,
                        help_text="Retention/deductible on the primary layer",
                        verbose_name="Primary Retention",
                    ),
                ),
                (
                    "primary_premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Premium paid to the primary carrier",
                        max_digits=15,
                        verbose_name="Primary Premium",
                    ),
                ),
                (
                    "excess_carrier",
                    models.CharField(
                        default="Technology Risk Retention Group, Inc.",
                        help_text="Name of the excess carrier (default: Corgi RRG)",
                        max_length=255,
                        verbose_name="Excess Carrier",
                    ),
                ),
                (
                    "excess_carrier_naic",
                    models.CharField(
                        blank=True,
                        help_text="NAIC code of the excess carrier",
                        max_length=20,
                        null=True,
                        verbose_name="Excess Carrier NAIC",
                    ),
                ),
                (
                    "excess_attachment_point",
                    models.IntegerField(
                        help_text="Point at which the excess layer attaches (= primary_limit)",
                        verbose_name="Excess Attachment Point",
                    ),
                ),
                (
                    "excess_limit",
                    models.IntegerField(
                        help_text="Excess layer limit in dollars (above attachment point)",
                        verbose_name="Excess Limit",
                    ),
                ),
                (
                    "excess_premium",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Premium retained by the excess carrier (Corgi RRG)",
                        max_digits=15,
                        verbose_name="Excess Premium",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this excess structure",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "policy",
                    models.OneToOneField(
                        help_text="The brokered primary policy this excess layer sits above",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excess_layer",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Excess Layer",
                "verbose_name_plural": "Policy Excess Layers",
                "db_table": "policy_excess_layers",
            },
        ),
        migrations.CreateModel(
            name="SurplusLinesFiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("diligent_search_complete", "Diligent Search Complete"),
                            ("filed", "Filed"),
                            ("stamped", "Stamped"),
                            ("overdue", "Overdue"),
                            ("exempt", "Exempt"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Filing Status",
                    ),
                ),
                (
                    "filing_state",
                    models.CharField(
                        help_text="State in which this surplus lines policy must be filed",
                        max_length=2,
                        verbose_name="Filing State",
                    ),
                ),
                (
                    "stamping_office",
                    models.CharField(
                        blank=True,
                        help_text="Name of the state surplus lines stamping office (e.g. SLSOC for CA)",
                        max_length=255,
                        null=True,
                        verbose_name="Stamping Office",
                    ),
                ),
                (
                    "surplus_lines_tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="State surplus lines tax rate as a decimal (e.g. 0.0350 for 3.5%)",
                        max_digits=6,
                        verbose_name="Surplus Lines Tax Rate",
                    ),
                ),
                (
                    "surplus_lines_tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated tax amount in dollars",
                        max_digits=15,
                        verbose_name="Surplus Lines Tax Amount",
                    ),
                ),
                (
                    "stamping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Stamping office fee in dollars (varies by state)",
                        max_digits=10,
                        verbose_name="Stamping Fee",
                    ),
                ),
                (
                    "diligent_search_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the diligent search of the admitted market was documented",
                        null=True,
                        verbose_name="Diligent Search Completed At",
                    ),
                ),
                (
                    "admitted_carriers_approached",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of admitted carriers approached with declination reasons",
                        verbose_name="Admitted Carriers Approached",
                    ),
                ),
                (
                    "diligent_search_document_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 key for the diligent search affidavit/documentation",
                        max_length=500,
                        null=True,
                        verbose_name="Diligent Search Document S3 Key",
                    ),
                ),
                (
                    "binding_date",
                    models.DateField(
                        help_text="Date the policy was bound (start of filing deadline clock)",
                        verbose_name="Binding Date",
                    ),
                ),
                (
                    "filing_deadline",
                    models.DateField(
                        help_text="Deadline for filing with the stamping office",
                        verbose_name="Filing Deadline",
                    ),
                ),
                (
                    "filed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the filing was actually submitted",
                        null=True,
                        verbose_name="Filed At",
                    ),
                ),
                (
                    "stamped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the stamping office confirmed the filing",
                        null=True,
                        verbose_name="Stamped At",
                    ),
                ),
                (
                    "stamping_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number issued by the stamping office",
                        max_length=100,
                        null=True,
                        verbose_name="Stamping Reference",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal compliance notes",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "policy",
                    models.OneToOneField(
                        help_text="The non-admitted policy requiring surplus lines filing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surplus_lines_filing",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surplus Lines Filing",
                "verbose_name_plural": "Surplus Lines Filings",
                "db_table": "surplus_lines_filings",
                "ordering": ["filing_deadline"],
                "indexes": [
                    models.Index(
                        fields=["status", "filing_deadline"],
                        name="surplus_lin_status_d4ad21_idx",
                    ),
                    models.Index(
                        fields=["filing_state", "status"],
                        name="surplus_lin_filing__001c9f_idx",
                    ),
                ],
            },
        ),
    ]
