# Generated by Django 5.1.4 on 2026-03-31 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0031_policyexcesslayer_surpluslinesfiling"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageModificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "requested_changes",
                    models.JSONField(
                        help_text="JSON dict describing the requested changes (e.g. new limits, added endorsements)",
                        verbose_name="Requested Changes",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Customer-provided reason for the modification request",
                        verbose_name="Reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was approved or denied",
                        null=True,
                        verbose_name="Reviewed At",
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes from the underwriter",
                        null=True,
                        verbose_name="Reviewer Notes",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="The policy to be modified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification_requests",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted the modification request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coverage_modification_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who approved or denied the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_modification_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coverage Modification Request",
                "verbose_name_plural": "Coverage Modification Requests",
                "db_table": "coverage_modification_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
