# Generated by Django 5.1.4 on 2026-03-31 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0032_add_coverage_modification_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarnedPremiumRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="Start of the reporting period (usually first day of month)",
                        verbose_name="Period Start",
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="End of the reporting period (usually last day of month)",
                        verbose_name="Period End",
                    ),
                ),
                (
                    "earned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Premium earned during this period (prorated portion of total premium)",
                        max_digits=15,
                        verbose_name="Earned Premium",
                    ),
                ),
                (
                    "unearned_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Premium not yet earned (remaining unearned balance at period end)",
                        max_digits=15,
                        verbose_name="Unearned Premium",
                    ),
                ),
                (
                    "calculation_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date this record was calculated",
                        verbose_name="Calculation Date",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earned_premium_records",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Earned Premium Record",
                "verbose_name_plural": "Earned Premium Records",
                "db_table": "earned_premium_records",
                "ordering": ["-period_start"],
                "unique_together": {("policy", "period_start", "period_end")},
            },
        ),
    ]
