# Generated by Django 5.1.4 on 2026-03-31 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_add_business_fields"),
        ("policies", "0033_earnedpremiumrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        help_text="Customer's preferred date for the review call",
                        verbose_name="Preferred Date",
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Preferred time in HH:MM format (e.g. 14:00)",
                        max_length=10,
                        verbose_name="Preferred Time",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/New_York",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "topics",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated topics the customer wants to discuss",
                        verbose_name="Topics to Discuss",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Any extra context from the customer",
                        verbose_name="Additional Notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confirmed_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Final confirmed date/time set by the AE",
                        null=True,
                        verbose_name="Confirmed Datetime",
                    ),
                ),
                (
                    "ae_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes from the Account Executive",
                        verbose_name="AE Notes",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_schedules",
                        to="organizations.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Schedule",
                "verbose_name_plural": "Review Schedules",
                "db_table": "review_schedules",
                "ordering": ["-created_at"],
            },
        ),
    ]
