# Generated by Django 5.1.4 on 2026-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0034_review_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="hubspot_deal_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of the corresponding HubSpot Deal for CRM sync",
                max_length=50,
                null=True,
                verbose_name="HubSpot Deal ID",
            ),
        ),
    ]
