# Generated by Django 5.2.13 on 2026-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0041_policy_hubspot_sync_hash_reconciled_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='revenuesplit',
            new_name='revenue_spl_transac_047120_idx',
            old_name='revenue_spl_transac_computed_idx',
        ),
        migrations.AlterField(
            model_name='revenuesplit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
