# Generated by Django 5.1.4 on 2026-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SLAMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("quote_turnaround", "Quote Turnaround"),
                            ("claim_acknowledgment", "Claim Acknowledgment"),
                            ("support_response", "Support Response"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Metric Type",
                    ),
                ),
                (
                    "target_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="SLA target in hours (e.g. 24.0 for 1 business day)",
                        max_digits=6,
                        verbose_name="Target Hours",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model type, e.g. 'quote', 'claim', 'support_ticket'",
                        max_length=50,
                        verbose_name="Entity Type",
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Primary key of the related entity",
                        verbose_name="Entity ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="When the SLA clock started",
                        verbose_name="Started At",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the SLA was satisfied (null = still open)",
                        null=True,
                        verbose_name="Completed At",
                    ),
                ),
                (
                    "breached",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if the SLA target was missed",
                        verbose_name="Breached",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "SLA Metric",
                "verbose_name_plural": "SLA Metrics",
                "db_table": "sla_metrics",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="sla_metrics_entity__bc74db_idx",
                    ),
                    models.Index(
                        fields=["metric_type", "breached"],
                        name="sla_metrics_metric__dbdcb3_idx",
                    ),
                ],
            },
        ),
    ]
