# Generated by Django 5.1.4 on 2026-01-14 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                ("file_type", models.CharField(max_length=50)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="Size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                ("s3_key", models.CharField(max_length=500)),
                ("s3_url", models.URLField(max_length=1000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("certificate", "Certificate"),
                            ("endorsement", "Endorsement"),
                            ("receipt", "Receipt"),
                            ("loss_run", "Loss Run Report"),
                        ],
                        default="policy",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the document (e.g., 'Errors & Omissions')",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(
                        blank=True,
                        help_text="Associated policy number if applicable",
                        max_length=50,
                        verbose_name="Policy Number",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective Date"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Expiration Date"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Document",
                "verbose_name_plural": "User Documents",
                "db_table": "user_documents",
                "ordering": ["category", "-created_at"],
            },
        ),
    ]
