# Generated by Django 5.1.4 on 2026-01-17 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_migrate_policy_documents_to_user_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpersonationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admin User",
                    ),
                ),
                (
                    "impersonated_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Impersonated User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impersonation Log",
                "verbose_name_plural": "Impersonation Logs",
                "db_table": "impersonation_logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
