# Generated by Django 5.1.4 on 2026-01-21 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_policy_number_to_array(apps, schema_editor):
    """Migrate existing policy_number values to policy_numbers array."""
    UserDocument = apps.get_model("users", "UserDocument")
    for doc in UserDocument.objects.all():
        if doc.policy_number:
            doc.policy_numbers = [doc.policy_number]
            doc.save(update_fields=["policy_numbers"])


def reverse_migrate_policy_numbers_to_single(apps, schema_editor):
    """Reverse migration: take first policy number from array."""
    UserDocument = apps.get_model("users", "UserDocument")
    for doc in UserDocument.objects.all():
        if doc.policy_numbers:
            doc.policy_number = doc.policy_numbers[0]
            doc.save(update_fields=["policy_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_impersonation_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdocument",
            name="policy_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="Associated policy numbers for this document",
                size=None,
                verbose_name="Policy Numbers",
            ),
        ),
        migrations.RunPython(
            migrate_policy_number_to_array, reverse_migrate_policy_numbers_to_single
        ),
        migrations.RemoveField(
            model_name="userdocument",
            name="policy_number",
        ),
    ]
