# Generated by Django 5.1.4 on 2026-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_add_role_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("ae", "Account Executive"),
                    ("ae_underwriting", "AE + Underwriting"),
                    ("bdr", "Business Development Rep"),
                    ("finance", "Finance"),
                    ("broker", "Broker"),
                    ("policyholder", "Policyholder"),
                ],
                default="policyholder",
                help_text="Policyholders can only access the portal.",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
