# Generated by Django 5.1.4 on 2026-03-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_add_active_session"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activesession",
            new_name="active_sess_user_id_ee13ad_idx",
            old_name="active_sess_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="activesession",
            new_name="active_sess_session_e7ea59_idx",
            old_name="active_sess_key_idx",
        ),
        migrations.AlterField(
            model_name="activesession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="activesession",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
    ]
