# Generated by Django 5.1.4 on 2026-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_add_totp_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="totpdevice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="totpdevice",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("ae", "Account Executive"),
                    ("ae_underwriting", "AE + Underwriting"),
                    ("bdr", "Business Development Rep"),
                    ("finance", "Finance"),
                    ("broker", "Broker"),
                    ("claims_adjuster", "Claims Adjuster"),
                    ("customer_support", "Customer Support"),
                    ("policyholder", "Policyholder"),
                ],
                db_index=True,
                default="policyholder",
                help_text="Policyholders can only access the portal.",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
