# Generated by Django 5.1.4 on 2026-03-31 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0017_rename_active_sess_user_active_idx_active_sess_user_id_ee13ad_idx_and_more",
        ),
        ("users", "0018_initial"),
    ]

    operations = []
