# Generated by Django 5.1.4 on 2026-04-02 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_merge_20260331_2123"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email used in the login attempt (always recorded)",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("otp", "Email OTP"),
                            ("password", "Password"),
                            ("refresh", "Token Refresh"),
                            ("impersonation", "Impersonation"),
                        ],
                        max_length=20,
                        verbose_name="Login Method",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Success"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reason for failed login (e.g. 'invalid_code', 'wrong_password', 'locked')",
                        max_length=100,
                        verbose_name="Failure Reason",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO 3166-1 alpha-2 country code from IP geolocation (if available)",
                        max_length=2,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for failed attempts where user could not be resolved",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Event",
                "verbose_name_plural": "Login Events",
                "db_table": "login_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="login_event_user_id_ab7d31_idx",
                    ),
                    models.Index(
                        fields=["email", "-created_at"],
                        name="login_event_email_887c86_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="login_event_ip_addr_e5e316_idx",
                    ),
                    models.Index(
                        fields=["success", "-created_at"],
                        name="login_event_success_682aba_idx",
                    ),
                ],
            },
        ),
    ]
