# Generated by Django 5.1.4 on 2026-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_loginevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hubspot_contact_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of the corresponding HubSpot Contact for CRM sync",
                max_length=50,
                null=True,
                verbose_name="HubSpot Contact ID",
            ),
        ),
    ]
