# Generated by Django 5.2.13 on 2026-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_two_factor_delivery_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='twofactordeliverylog',
            new_name='two_factor__user_id_2aa0c8_idx',
            old_name='two_factor__user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='twofactordeliverylog',
            new_name='two_factor__status_0d9142_idx',
            old_name='two_factor__status_idx',
        ),
        migrations.AlterField(
            model_name='twofactordeliverylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='twofactordeliverylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twofactordeliverylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At'),
        ),
    ]
