# Generated by Django 5.1.4 on 2026-03-31 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("policies", "0029_policy_continuity_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to refund in USD.",
                        max_digits=15,
                        verbose_name="Refund Amount",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("cancellation", "Policy Cancellation"),
                            ("duplicate_charge", "Duplicate Charge"),
                            ("billing_error", "Billing Error"),
                            ("coverage_not_needed", "Coverage No Longer Needed"),
                            ("underwriting_rejection", "Underwriting Rejection"),
                            ("customer_dissatisfaction", "Customer Dissatisfaction"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Reason category for the refund request.",
                        max_length=30,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional details about the refund reason.",
                        verbose_name="Reason Detail",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved/Denied At"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the Stripe refund was successfully processed.",
                        null=True,
                        verbose_name="Processed At",
                    ),
                ),
                (
                    "denial_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation shown to the customer when denied.",
                        verbose_name="Denial Reason",
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe refund object ID (re_...) after processing.",
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Refund ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="The Stripe PaymentIntent being refunded.",
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who approved or denied this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved/Denied By",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="The policy this refund is related to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="User who submitted the refund request.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Refund Request",
                "verbose_name_plural": "Refund Requests",
                "db_table": "refund_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
