# Generated by Django 5.1.4 on 2026-03-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_integration", "0002_add_dunning_record"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dunningrecord",
            new_name="dunning_rec_status_e45390_idx",
            old_name="dunning_status_retry_idx",
        ),
        migrations.AlterField(
            model_name="dunningrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="dunningrecord",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this dunning record was resolved (payment recovered or policy cancelled).",
                null=True,
                verbose_name="Resolved At",
            ),
        ),
        migrations.AlterField(
            model_name="dunningrecord",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
    ]
