# Generated by Django 5.1.4 on 2026-03-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        db_index=True,
                        help_text="Internal coverage type slug (e.g. 'commercial-general-liability')",
                        max_length=100,
                        unique=True,
                        verbose_name="Coverage Type Slug",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable product name shown to customers",
                        max_length=255,
                        verbose_name="Display Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Short product description shown in the portal",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this product is available for purchase",
                        verbose_name="Active",
                    ),
                ),
                (
                    "min_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum available aggregate limit in dollars",
                        null=True,
                        verbose_name="Minimum Limit ($)",
                    ),
                ),
                (
                    "max_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum available aggregate limit in dollars",
                        null=True,
                        verbose_name="Maximum Limit ($)",
                    ),
                ),
                (
                    "available_retentions",
                    models.JSONField(
                        default=list,
                        help_text="List of available retention/deductible options in dollars, e.g. [500, 1000, 2500]",
                        verbose_name="Available Retentions",
                    ),
                ),
                (
                    "rating_tier",
                    models.CharField(
                        choices=[
                            ("tier1_instant", "Tier 1 — Instant Quote"),
                            ("tier2_brokered_form", "Tier 2 — Brokered with Form"),
                            ("tier3_brokered_intent", "Tier 3 — Brokered Intent Only"),
                        ],
                        default="tier1_instant",
                        help_text="How premiums are calculated for this product",
                        max_length=30,
                        verbose_name="Rating Tier",
                    ),
                ),
                (
                    "requires_review",
                    models.BooleanField(
                        default=False,
                        help_text="If true, all quotes for this product will go to needs_review status",
                        verbose_name="Requires Underwriter Review",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for underwriters / product team",
                        verbose_name="Admin Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Configuration",
                "verbose_name_plural": "Product Configurations",
                "db_table": "product_configurations",
                "ordering": ["display_name"],
            },
        ),
    ]
