# Generated by Django 5.2.13 on 2026-04-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hubspotsyncfailure',
            new_name='hubspot_syn_event_t_5c9160_idx',
            old_name='hubspot_syn_event_t_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspotsyncfailure',
            new_name='hubspot_syn_resolve_144775_idx',
            old_name='hubspot_syn_resolve_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspotsynclog',
            new_name='hubspot_syn_object__13c94d_idx',
            old_name='hubspot_syn_object__f0b4d7_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspotsynclog',
            new_name='hubspot_syn_django__44cba5_idx',
            old_name='hubspot_syn_django__2f1a8e_idx',
        ),
        migrations.RenameIndex(
            model_name='hubspotsynclog',
            new_name='hubspot_syn_success_8a38db_idx',
            old_name='hubspot_syn_success_8c3d5b_idx',
        ),
    ]
