# Generated by Django 5.1.4 on 2026-03-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="prefix",
            field=models.CharField(
                help_text="First 16 characters of the raw key, used for fast lookup",
                max_length=16,
                unique=True,
                verbose_name="Prefix",
            ),
        ),
    ]
