# Generated by Django 5.1.4 on 2026-03-05 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_api", "0002_increase_prefix_length"),
        ("organizations", "0003_create_personal_orgs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_keys",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.CreateModel(
            name="ApiKeyInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=64, unique=True, verbose_name="Token"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "partner_first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "partner_last_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "partner_org_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "partner_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "api_key",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite",
                        to="external_api.apikey",
                        verbose_name="API Key",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_key_invites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Invite",
                "verbose_name_plural": "API Key Invites",
                "db_table": "external_api_key_invites",
                "ordering": ["-created_at"],
            },
        ),
    ]
