# Generated by Django 5.1.4 on 2026-03-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_webhook_delivery_system"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhooks_we_status_18db77_idx",
            old_name="webhookdeli_status_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhooks_we_endpoin_298618_idx",
            old_name="webhookdeli_endpoint_event_idx",
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="error_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Error detail from last failed attempt",
                verbose_name="Error Message",
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="payload",
            field=models.JSONField(
                help_text="JSON payload sent to the endpoint", verbose_name="Payload"
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="response_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Truncated response body from last attempt",
                verbose_name="Response Body",
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="response_status",
            field=models.IntegerField(
                blank=True,
                help_text="HTTP status code from last delivery attempt",
                null=True,
                verbose_name="HTTP Response Status",
            ),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive endpoints receive no deliveries",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="secret",
            field=models.CharField(
                help_text="Secret used to sign HMAC-SHA256 payload signatures",
                max_length=255,
                verbose_name="Signing Secret",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="subscribed_events",
            field=models.JSONField(
                default=list,
                help_text="List of event types this endpoint subscribes to",
                verbose_name="Subscribed Events",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
        migrations.AlterField(
            model_name="webhookendpoint",
            name="url",
            field=models.URLField(
                help_text="HTTPS URL that will receive POST requests",
                max_length=500,
                verbose_name="Endpoint URL",
            ),
        ),
    ]
