# Generated by Django 5.1.4 on 2026-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Legal name of the insurance carrier",
                        max_length=255,
                        unique=True,
                        verbose_name="Carrier Name",
                    ),
                ),
                (
                    "am_best_rating",
                    models.CharField(
                        blank=True,
                        help_text="AM Best financial strength rating (e.g. A, A+, A-)",
                        max_length=10,
                        verbose_name="AM Best Rating",
                    ),
                ),
                (
                    "appetite_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the carrier's underwriting appetite and preferred risks",
                        verbose_name="Appetite Description",
                    ),
                ),
                (
                    "commission_rates",
                    models.JSONField(
                        default=dict,
                        help_text='JSON object mapping coverage types to commission rates, e.g. {"tech-eo": 0.15, "cyber": 0.12}',
                        verbose_name="Commission Rates",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person at the carrier",
                        max_length=255,
                        verbose_name="Contact Name",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
            ],
            options={
                "verbose_name": "Carrier",
                "verbose_name_plural": "Carriers",
                "db_table": "carriers",
                "ordering": ["name"],
            },
        ),
    ]
