# Generated by Django 5.1.4 on 2026-03-28 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formdefinition",
            name="unique_form_slug_version",
        ),
        migrations.RenameIndex(
            model_name="formdefinition",
            new_name="form_defini_slug_ddc1c0_idx",
            old_name="form_defini_slug_active_idx",
        ),
        migrations.RenameIndex(
            model_name="formdefinition",
            new_name="form_defini_coverag_f0ff87_idx",
            old_name="form_defini_coverage_type_idx",
        ),
        migrations.RenameIndex(
            model_name="formsubmission",
            new_name="form_submis_quote_i_b78cb8_idx",
            old_name="form_sub_quote_formdef_idx",
        ),
        migrations.AlterUniqueTogether(
            name="formdefinition",
            unique_together={("slug", "version")},
        ),
    ]
