# Generated by Django 5.1.4 on 2026-02-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("policies", "0023_alter_policy_monthly_premium"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "producer_type",
                    models.CharField(
                        choices=[
                            ("bdr", "BDR"),
                            ("ae", "AE"),
                            ("am", "AM"),
                            ("broker", "Broker"),
                            ("agent", "Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Producer",
                "verbose_name_plural": "Producers",
                "db_table": "producers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyProducer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage of GWP"),
                            ("flat", "Flat Fee"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Commission rate as decimal (e.g., 0.1500 for 15%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flat fee commission amount, or calculated amount for percentage",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producers",
                        to="policies.policy",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_assignments",
                        to="producers.producer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Producer",
                "verbose_name_plural": "Policy Producers",
                "db_table": "policy_producers",
                "unique_together": {("policy", "producer")},
            },
        ),
    ]
