# Generated by Django 5.1.4 on 2026-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Producer's email address",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this producer is currently active",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Insurance producer license number",
                max_length=50,
                verbose_name="License Number",
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="name",
            field=models.CharField(
                help_text="Full name of the producer",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="producer_type",
            field=models.CharField(
                choices=[
                    ("bdr", "BDR"),
                    ("ae", "AE"),
                    ("am", "AM"),
                    ("broker", "Broker"),
                    ("agent", "Agent"),
                ],
                help_text="Type of producer role",
                max_length=20,
                verbose_name="Producer Type",
            ),
        ),
    ]
