# Generated by Django 5.1.4 on 2026-03-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0032_add_coverage_modification_request"),
        ("producers", "0002_alter_producer_email_alter_producer_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission payout amount in USD",
                        max_digits=15,
                        verbose_name="Payout Amount",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("percentage_of_premium", "Percentage of Premium"),
                            ("flat_fee", "Flat Fee"),
                            ("tiered", "Tiered Rate"),
                        ],
                        default="percentage_of_premium",
                        max_length=30,
                        verbose_name="Calculation Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("calculated", "Calculated"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="calculated",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the payout was marked as paid",
                        null=True,
                        verbose_name="Paid At",
                    ),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Connect transfer ID if paid via Stripe",
                        max_length=100,
                        verbose_name="Stripe Transfer ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this payout",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_payouts",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_payouts",
                        to="producers.producer",
                        verbose_name="Producer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Payout",
                "verbose_name_plural": "Commission Payouts",
                "db_table": "commission_payouts",
                "ordering": ["-created_at"],
            },
        ),
    ]
