# Generated by Django 5.1.4 on 2026-03-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when this record was created",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledreport",
            name="extra_filters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional filters passed to the report generator (e.g. carrier, coverage_type)",
                verbose_name="Extra Filters",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledreport",
            name="recipients",
            field=models.JSONField(
                default=list,
                help_text="JSON array of email addresses to send the report to",
                verbose_name="Recipients",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledreport",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when this record was last updated",
                verbose_name="Updated At",
            ),
        ),
    ]
