# Generated by Django 5.1.4 on 2026-01-22 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("policies", "0010_expand_lob_code_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Claim Number"
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(max_length=255, verbose_name="Organization Name"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the claim/incident",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("closed", "Closed"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes (not visible to customer)",
                        verbose_name="Admin Notes",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="policies.policy",
                        verbose_name="Policy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim",
                "verbose_name_plural": "Claims",
                "db_table": "claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                ("file_type", models.CharField(max_length=50)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="Size in bytes")),
                ("mime_type", models.CharField(max_length=100)),
                ("s3_key", models.CharField(max_length=500)),
                ("s3_url", models.URLField(max_length=1000)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="claims.claim",
                        verbose_name="Claim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Document",
                "verbose_name_plural": "Claim Documents",
                "db_table": "claim_documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
