# Generated by Django 5.1.4 on 2026-02-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0003_alter_claim_admin_notes_alter_claim_description_and_more"),
        ("organizations", "0002_organization_is_personal"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="organizations.organization",
            ),
        ),
    ]
