# Generated by Django 5.1.4 on 2026-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0006_add_claim_resolution_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="submitted",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
