# Generated by Django 5.1.4 on 2026-03-31 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Article title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier (auto-generated from title if blank)",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Article body in Markdown format",
                        verbose_name="Content",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("product-knowledge", "Product Knowledge"),
                            ("underwriting-guidelines", "Underwriting Guidelines"),
                            ("claim-procedures", "Claim Procedures"),
                            ("sales-playbook", "Sales Playbook"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only published articles are visible to staff",
                        verbose_name="Published",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags for search and filtering",
                        max_length=255,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this article has been viewed",
                        verbose_name="View Count",
                    ),
                ),
                (
                    "last_reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this article was last reviewed for accuracy",
                        null=True,
                        verbose_name="Last Reviewed At",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "last_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Article",
                "verbose_name_plural": "Knowledge Articles",
                "db_table": "knowledge_articles",
                "ordering": ["category", "title"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"],
                        name="knowledge_a_categor_99d84b_idx",
                    ),
                    models.Index(
                        fields=["is_published", "-created_at"],
                        name="knowledge_a_is_publ_643e26_idx",
                    ),
                ],
            },
        ),
    ]
