# Generated by Django 5.1.4 on 2026-03-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quotes", "0048_alter_quote_quote_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokeredQuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        help_text="e.g. workers-comp",
                        max_length=50,
                        verbose_name="Coverage Type",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        help_text="e.g. pie-insurance",
                        max_length=100,
                        verbose_name="Carrier",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "form_payload",
                    models.JSONField(
                        help_text="Coverage-specific form data sent to the automation Lambda",
                        verbose_name="Form Payload",
                    ),
                ),
                (
                    "premium_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Premium Amount",
                    ),
                ),
                (
                    "decline_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Decline Reason"
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, null=True, verbose_name="Error Log"),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokered_quote_requests",
                        to="quotes.quote",
                        verbose_name="Quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brokered Quote Request",
                "verbose_name_plural": "Brokered Quote Requests",
                "db_table": "brokered_quote_requests",
                "unique_together": {("quote", "coverage_type")},
            },
        ),
    ]
