# Generated by Django 5.1.4 on 2026-03-16 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("brokered", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brokeredquoterequest",
            options={
                "verbose_name": "Brokered Coverage Request",
                "verbose_name_plural": "Brokered Coverage Requests",
            },
        ),
    ]
