# Generated by Django 5.1.4 on 2026-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokered", "0002_rename_brokered_quote_request_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="quote_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Quote URL"
            ),
        ),
    ]
