# Generated by Django 5.1.4 on 2026-03-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokered", "0003_add_quote_url_to_brokered_quote_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("quoted", "Quoted"),
                    ("declined", "Declined"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
