# Generated by Django 5.1.4 on 2026-03-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokered", "0004_rename_completed_to_quoted_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brokeredquoterequest",
            name="error_log",
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="run_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Run ID"
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="form_payload",
            field=models.JSONField(
                help_text="Coverage-specific form data sent to the Skyvern workflow",
                verbose_name="Form Payload",
            ),
        ),
    ]
