# Generated by Django 5.1.4 on 2026-03-31 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokered", "0007_add_underwriter_fields"),
        ("quotes", "0056_encrypt_existing_federal_ein"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brokeredquoterequest",
            options={
                "verbose_name": "Brokered Quote Request",
                "verbose_name_plural": "Brokered Quote Requests",
            },
        ),
        migrations.AlterUniqueTogether(
            name="brokeredquoterequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="additional_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Additional Notes"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="aggregate_limit",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Aggregate Limit"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="blocker_detail",
            field=models.TextField(
                blank=True, default="", verbose_name="Blocker Detail"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="blocker_type",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Blocker Type"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="client_contact_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Client Contact URL",
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="client_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Client Email"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="company_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Company Name"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="coverage_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of coverage type codes, e.g. ['cgl', 'cyber']",
                verbose_name="Coverage Types",
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="custom_product_created",
            field=models.BooleanField(
                default=False, verbose_name="Custom Product Created"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="django_admin_url",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Django Admin URL"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="docs_uploaded",
            field=models.BooleanField(default=False, verbose_name="Docs Uploaded"),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="is_bound",
            field=models.BooleanField(default=False, verbose_name="Is Bound"),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="missing_docs_note",
            field=models.TextField(
                blank=True, default="", verbose_name="Missing Documents Note"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="per_occurrence_limit",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Per Occurrence Limit",
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="requested_coverage_detail",
            field=models.TextField(
                blank=True, default="", verbose_name="Requested Coverage Detail"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="requester_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Requester Email"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="retention",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Retention"
            ),
        ),
        migrations.AddField(
            model_name="brokeredquoterequest",
            name="stripe_confirmed",
            field=models.BooleanField(default=False, verbose_name="Stripe Confirmed"),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_brokered_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="carrier",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Carrier"
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="coverage_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Single coverage type for Skyvern automation, e.g. workers-comp",
                max_length=50,
                verbose_name="Coverage Type (Skyvern)",
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="external_quote_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="External Quote Number",
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="form_payload",
            field=models.JSONField(
                blank=True,
                help_text="Coverage-specific form data sent to the Skyvern workflow",
                null=True,
                verbose_name="Form Payload",
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                db_index=True,
                default="medium",
                max_length=10,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brokered_quote_requests",
                to="quotes.quote",
                verbose_name="Quote",
            ),
        ),
        migrations.AlterField(
            model_name="brokeredquoterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("submitted", "Submitted"),
                    ("otm", "Out to Market"),
                    ("quoted", "Quoted"),
                    ("on_hold", "On Hold"),
                    ("denied", "Denied"),
                    ("recalled", "Recalled"),
                    ("blocked", "Blocked"),
                    ("stalled", "Stalled"),
                    ("cancelled", "Cancelled"),
                    ("bound", "Bound"),
                ],
                db_index=True,
                default="received",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
