# Generated by Django 5.1.4 on 2026-03-31 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("policies", "0032_add_coverage_modification_request"),
        ("quotes", "0054_add_soft_delete_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "recipient",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary recipient email address",
                        max_length=254,
                        verbose_name="Recipient",
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Subject")),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Full HTML body of the email",
                        verbose_name="Body (HTML)",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Sent At"
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID returned by the email provider (Resend)",
                        max_length=255,
                        null=True,
                        verbose_name="Provider Message ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("dev_log", "Dev Log (not sent)"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=20,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if delivery failed",
                        null=True,
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "related_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="policies.policy",
                        verbose_name="Related Policy",
                    ),
                ),
                (
                    "related_quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="quotes.quote",
                        verbose_name="Related Quote",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user who triggered this email (null = system/automated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sent By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "db_table": "email_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "sent_at"],
                        name="email_logs_recipie_a5d214_idx",
                    ),
                    models.Index(
                        fields=["related_policy", "sent_at"],
                        name="email_logs_related_7bbe6f_idx",
                    ),
                    models.Index(
                        fields=["related_quote", "sent_at"],
                        name="email_logs_related_5c5761_idx",
                    ),
                ],
            },
        ),
    ]
