# Generated by Django 5.2.13 on 2026-04-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailcontext'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailcontext',
            new_name='email_conte_expires_b79e03_idx',
            old_name='email_ctx_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcontext',
            new_name='email_conte_salespe_580b4b_idx',
            old_name='email_ctx_sp_exp_idx',
        ),
    ]
